animal = {
	"heixiong": {
		"name": "黑熊",
		"HP": 0,
		"MP": 0,
		"AP": 0,
		"SP": 0,
		"Speed": 0,
		"growth": 1.180,
		"high_growth": 1.231,
		"title_level": 0,
		"skills": [],
		"five_elements": [0, 0, 100, 0, 0],
		"run": ["", ""],
		"stand": ["shape.wdf", "0x8F63C7D7"],
		"walk": ["shape.wdf", "0x0693E4D6"],
		"hit": ["", ""],
		"beaten": ["", ""],
		"defence": ["", ""],
		"magic": ["", ""],
	},
	"huangniu": {
		"name": "黄牛",
		"HP": ,
		"MP": ,
		"AP": ,
		"SP": ,
		"Speed": ,
		"growth": ,
		"high_growth": ,
		"title_level": ,
		"skills": [],
		"run": ["", ""],
		"stand": ["shape.wdf", "0x959E86AC"],
		"walk": ["shape.wdf", "0xA8EF83BC"],
		"hit": ["", ""],
		"beaten": ["", ""],
		"defence": ["", ""],
		"magic": ["", ""],
	},
	"bingyuhe": {
		"name": "冰羽鹤",
		"HP": ,
		"MP": ,
		"AP": ,
		"SP": ,
		"Speed": ,
		"growth": ,
		"high_growth": ,
		"title_level": ,
		"skills": [],
		"run": ["", ""],
		"stand": ["shape.wdf", "0x712DD99A"],  # DFBB7D6C
		"walk": ["shape.wdf", "0x2DA2D22E"],
		"hit": ["", ""],
		"beaten": ["", ""],
		"defence": ["", ""],
		"magic": ["", ""],
	},
	"jinqianbao": {
		"name": "金钱豹",
		"HP": ,
		"MP": ,
		"AP": ,
		"SP": ,
		"Speed": ,
		"growth": ,
		"high_growth": ,
		"title_level": ,
		"skills": [],
		"run": ["", ""],
		"stand": ["shape.wdf", "0x5A580A0C"],
		"walk": ["shape.wdf", "0xFD78B79C"],
		"hit": ["", ""],
		"beaten": ["", ""],
		"defence": ["", ""],
		"magic": ["", ""],
	},
	"changongtu": {
		"name": "蟾宫兔",
		"HP": ,
		"MP": ,
		"AP": ,
		"SP": ,
		"Speed": ,
		"growth": ,
		"high_growth": ,
		"title_level": ,
		"skills": [],
		"run": ["", ""],
		"stand": ["shape.wdf", "0x87F370B5"],
		"walk": ["", ""],
		"hit": ["shape.wdf", "0xC8B56AAB"],
		"beaten": ["", ""],
		"defence": ["", ""],
		"magic": ["", ""],
	},
	"xianpingque": {
		"name": "仙屏雀",
		"HP": ,
		"MP": ,
		"AP": ,
		"SP": ,
		"Speed": ,
		"growth": ,
		"high_growth": ,
		"title_level": ,
		"skills": [],
		"run": ["", ""],
		"stand": ["shape.wdf", "0xD4B0D0B3"],
		"walk": ["shape.wdf", "0xF9B81AB9"],
		"hit": ["", ""],
		"beaten": ["", ""],
		"defence": ["", ""],
		"magic": ["", ""],
	},
}


	"": {
		"name": "",
		"HP": ,
		"MP": ,
		"AP": ,
		"SP": ,
		"Speed": ,
		"growth": ,
		"high_growth": ,
		"title_level": ,
		"skills": [],
		"run": ["", ""],
		"stand": ["", ""],
		"walk": ["", ""],
		"hit": ["", ""],
		"beaten": ["", ""],
		"defence": ["", ""],
		"magic": ["", ""],
	},