monsters = {
  "feiyu": {
    "name": "飞鱼",
    "HP": 42,
    "MP": 0,
    "AP": 60,
    "SP": 18,
    "speed": 17,
    "growth": 1.033,
    "high_growth": 1.208,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 40,
    "soil": 0,
    "water": 60,
    "fire": 0,
    "run": ["shape.wdf", "0x4B5AA8A9"],
    "stand": ["shape.wdf", "0xBD7EF6B7"],
    "walk": ["shape.wdf", "0x1D87262C"],
    "hit": ["shape.wdf", "0x6B382C76"],
    "beaten": ["shape.wdf", "0x4E033690"],
    "defence": ["shape.wdf", "0xD0829F8F"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xF225F2D5"]
  },
  "chanchu": {
    "name": "蟾蜍",
    "HP": 66,
    "MP": 0,
    "AP": 42,
    "SP": 14,
    "speed": 14,
    "growth": 1.035,
    "high_growth": 1.207,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 75,
    "water": 25,
    "fire": 0,
    "run": ["shape.wdf", "0x232651D3"],
    "stand": ["shape.wdf", "0xB548B2E8"],
    "walk": ["shape.wdf", "0xB0E02259"],
    "hit": ["shape.wdf", "0xE325DA76"],
    "beaten": ["shape.wdf", "0xFBAECC68"],
    "defence": ["shape.wdf", "0x77254EFE"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xD69D74DA"]
  },
  "zhizhu": {
    "name": "蜘蛛",
    "HP": 48,
    "MP": 0,
    "AP": 48,
    "SP": 9,
    "speed": 9,
    "growth": 1.038,
    "high_growth": 1.206,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 50,
    "soil": 50,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xD317B92D"],
    "stand": ["shape.wdf", "0x00A896B4"],
    "walk": ["shape.wdf", "0x2D13702B"],  # 1332
    "hit": ["shape.wdf", "0x66228768"],
    "beaten": ["shape.wdf", "0x79C51CA1"],
    "defence": ["shape.wdf", "0x78251D69"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x7B124653"]
  },
  "dushe": {
    "name": "毒蛇",
    "HP": 72,
    "MP": 0,
    "AP": 120,
    "SP": 18,
    "speed": 17,
    "growth": 1.034,
    "high_growth": 1.207,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 65,
    "soil": 0,
    "water": 35,
    "fire": 0,
    "run": ["shape.wdf", "0x41C928FC"],
    "stand": ["shape.wdf", "0xAE6FFCA4"],  # 1116
    "walk": ["shape.wdf", "0x90E6F577"],
    "hit": ["shape.wdf", "0x30CA6EF0"],  # 331   # 23
    "beaten": ["shape.wdf", "0x6945703C"],
    "defence": ["shape.wdf", "0x046E69D3"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x4FDE0C86"]
  },
  "bianfu": {
    "name": "蝙蝠",
    "HP": 60,
    "MP": 0,
    "AP": 72,
    "SP": 21,
    "speed": 20,
    "growth": 1.032,
    "high_growth": 1.208,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 60,
    "soil": 0,
    "water": 0,
    "fire": 40,
    "run": ["shape.wdf", "0x7A965E8E"],
    "stand": ["shape.wdf", "0x0749E553"],
    "walk": ["shape.wdf", "0xDBA9BE37"],
    "hit": ["shape.wdf", "0xC7766014"],
    "beaten": ["shape.wdf", "0x154302AE"],
    "defence": ["shape.wdf", "0x3105EDD1"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x10614BC6"]
  },
  "haigui": {
    "name": "海龟",
    "HP": 144,
    "MP": 0,
    "AP": 36,
    "SP": -37,
    "speed": -36,
    "growth": 1.039,
    "high_growth": 1.206,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 20,
    "water": 80,
    "fire": 0,
    "run": ["shape.wdf", "0xA912D4C1"],
    "stand": ["shape.wdf", "0x02542231"],
    "walk": ["shape.wdf", "0x545A24CA"],
    "hit": ["shape.wdf", "0xB0E742C3"],
    "beaten": ["shape.wdf", "0xC1BE763B"],
    "defence": ["shape.wdf", "0x73E169FD"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x4E4577E9"]
  },
  "xiaowuye": {
    "name": "小五叶",
    "HP": 144,
    "MP": 0,
    "AP": 20,
    "SP": 51,
    "speed": 44,
    "growth": 1.15,
    "high_growth": 1.15,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "yinhu": {
    "name": "银狐",
    "HP": 96,
    "MP": 0,
    "AP": 114,
    "SP": 37,
    "speed": 35,
    "growth": 1.066,
    "high_growth": 1.202,
    "title_level": 0,
    "skills": [],
    "gold": 35,
    "wood": 0,
    "soil": 0,
    "water": 65,
    "fire": 0,
    "run": ["shape.wdf", "0x532A404C"],
    "jag": ["shape.wdf", "0x0FF44F45"],
    "stand": ["shape.wdf", "0x3CDBAFB2"],  # 站立
    "stand_normal": ["shape.wdf", "0x3ADFAA02"],  # 回头舔
    "walk": ["shape.wdf", "0x0E6210D6"],
    "hit": ["shape.wdf", "0xB6DB9CCB"],
    "beaten": ["shape.wdf", "0x2112F5F7"],
    "defence": ["shape.wdf", "0xF0ACEB35"],
    "magic": ["shape.wdf", "0x897A5492"],
    "beaten_down": ["shape.wdf", "0xFF27CA9E"],
    "static": ["", "0x"]
  },
  "daocaoren": {
    "name": "稻草人",
    "HP": 62,
    "MP": 78,
    "AP": 92,
    "SP": 54,
    "speed": 41,
    "growth": 1.304,
    "high_growth": 1.304,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "houmao": {
    "name": "猴毛",
    "HP": 150,
    "MP": 90,
    "AP": 520,
    "SP": 244,
    "speed": 300,
    "growth": 0.814,
    "high_growth": 0.814,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "tuyao": {
    "name": "兔妖",
    "HP": 108,
    "MP": 0,
    "AP": 84,
    "SP": 12,
    "speed": 12,
    "growth": 1.04,
    "high_growth": 1.205,
    "title_level": 1,
    "skills": [],
    "gold": 35,
    "wood": 65,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xA6653EA8"],
    "stand": ["shape.wdf", "0x210F5951"],
    "walk": ["shape.wdf", "0x46242998"],
    "hit": ["shape.wdf", "0x441588C8"],
    "beaten": ["shape.wdf", "0xFC527CFF"],
    "defence": ["shape.wdf", "0xED788B3D"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x6EEFA438"]
  },
  "yangtouguai": {
    "name": "羊头怪",
    "HP": 90,
    "MP": 0,
    "AP": 78,
    "SP": 6,
    "speed": 6,
    "growth": 1.034,
    "high_growth": 1.207,
    "title_level": 1,
    "skills": [],
    "gold": 0,
    "wood": 55,
    "soil": 0,
    "water": 45,
    "fire": 0,
    "run": ["shape.wdf", "0x05F5FDA1"],
    "stand": ["shape.wdf", "0x7FCF1B5C"],
    "walk": ["shape.wdf", "0x1F263139"],
    "hit": ["shape.wdf", "0xE8104475"],
    "beaten": ["shape.wdf", "0xE4042BBF"],
    "defence": ["shape.wdf", "0xD463B910"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x8EE3FB9A"]
  },
  "zhuguai": {
    "name": "猪怪",
    "HP": 102,
    "MP": 0,
    "AP": 72,
    "SP": 0,
    "speed": 0,
    "growth": 1.037,
    "high_growth": 1.206,
    "title_level": 1,
    "skills": [],
    "gold": 40,
    "wood": 0,
    "soil": 60,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x224A5540"],
    "stand": ["shape.wdf", "0x7E3B3A2C"],
    "walk": ["shape.wdf", "0x99EE8435"],
    "hit": ["shape.wdf", "0xA5A50DD2"],
    "beaten": ["shape.wdf", "0xC8406125"],
    "defence": ["shape.wdf", "0x7012CFD1"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x5034A927"]
  },
  "yecha": {
    "name": "夜叉",
    "HP": 108,
    "MP": 96,
    "AP": 60,
    "SP": 12,
    "speed": 12,
    "growth": 1.037,
    "high_growth": 1.206,
    "title_level": 1,
    "skills": [[10, "diyuliehuo"],[30, "tianleinuhuo"],[50, "sanweizhenhuo"],[70, "liehuojiaoyang"]],
    "gold": 10,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 90,
    "run": ["shape.wdf", "0x0A287A80"],
    "stand": ["shape.wdf", "0x8140F72E"],
    "walk": ["shape.wdf", "0xA3545B8E"],
    "hit": ["shape.wdf", "0x1E2DDE33"],
    "beaten": ["shape.wdf", "0x678383BC"],
    "defence": ["shape.wdf", "0xA8FF07E2"],
    "magic": ["shape.wdf", "0xB2D419B5"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xE3E15EAC"]
  },
  "jiading": {
    "name": "家丁",
    "HP": 120,
    "MP": 0,
    "AP": 84,
    "SP": 6,
    "speed": 6,
    "growth": 1.035,
    "high_growth": 1.207,
    "title_level": 1,
    "skills": [],
    "gold": 35,
    "wood": 0,
    "soil": 65,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x942EBC96"],
    "jag": ["shape.wdf", "0xD945737B"],
    "stand_normal": ["shape.wdf", "0x7260A22B"],  # 站立背手
    "stand": ["shape.wdf", "0x19F4F169"], 
    "walk": ["shape.wdf", "0x71253EE7"],
    "hit": ["shape.wdf", "0xAE5C76F4"],
    "beaten": ["shape.wdf", "0x4F0800B0"],
    "defence": ["shape.wdf", "0xB1E2C93E"],
    "magic": ["shape.wdf", "0x30FC49F4"],
    "beaten_down": ["shape.wdf", "0x4AA0CD72"],
    "static": ["", "0x"]
  },
  "xiaoyao": {
    "name": "小妖",
    "HP": 108,
    "MP": 0,
    "AP": 108,
    "SP": 6,
    "speed": 6,
    "growth": 1.04,
    "high_growth": 1.205,
    "title_level": 1,
    "skills": [],
    "gold": 0,
    "wood": 40,
    "soil": 60,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x22D74D50"],
    "stand": ["shape.wdf", "0x0109395D"],
    "walk": ["shape.wdf", "0x7FBBA65B"],
    "hit": ["shape.wdf", "0xDA4C1796"],
    "beaten": ["shape.wdf", "0x85C294BA"],
    "defence": ["shape.wdf", "0x68C7CDF5"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xA008B525"]
  },
  "niuyao": {
    "name": "牛妖",
    "HP": 120,
    "MP": 0,
    "AP": 114,
    "SP": 12,
    "speed": 11,
    "growth": 1.044,
    "high_growth": 1.204,
    "title_level": 1,
    "skills": [],
    "gold": 65,
    "wood": 0,
    "soil": 35,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x326D00FE"],
    "stand": ["shape.wdf", "0xDEC9CC5B"],
    "walk": ["shape.wdf", "0x5274F324"],
    "hit": ["shape.wdf", "0x7FBB3BAC"],
    "beaten": ["shape.wdf", "0x51A98BB9"],
    "defence": ["shape.wdf", "0x1CD638BF"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xF58E06E8"]
  },
  "yegou": {
    "name": "野狗",
    "HP": 84,
    "MP": 0,
    "AP": 90,
    "SP": 31,
    "speed": 30,
    "growth": 1.041,
    "high_growth": 1.205,
    "title_level": 1,
    "skills": [],
    "gold": 0,
    "wood": 50,
    "soil": 0,
    "water": 50,
    "fire": 0,
    "run": ["shape.wdf", "0xF6210AA0"],  # 1536
    "jag": ["shape.wdf", "0x8A013203"],  # 1536
    "stand_normal": ["shape.wdf", "0xA94BB647"],  # ZHANLI
    "stand": ["shape.wdf", "0xB1FF146D"],
    "move": ["shape.wdf", "0x1621B9A4"],
    "walk": ["shape.wdf", "0xCB14A5E2"],
    "hit": ["shape.wdf", "0xAE415B39"],
    "beaten": ["shape.wdf", "0x2C78498A"],
    "defence": ["shape.wdf", "0x64537853"],
    "magic": ["shape.wdf", "0xD1C83AD0"],
    "beaten_down": ["shape.wdf", "0xF6739CAE"],
    "static": ["", "0x"]
  },
  "wushi": {
    "name": "武士",
    "HP": 120,
    "MP": 0,
    "AP": 132,
    "SP": 12,
    "speed": 11,
    "growth": 1.045,
    "high_growth": 1.204,
    "title_level": 1,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 50,
    "water": 0,
    "fire": 50,
    "run": ["shape.wdf", "0xB3EC1FAB"],
    "stand": ["shape.wdf", "0xE01F9B56"],
    "walk": ["shape.wdf", "0x46904ADE"],
    "hit": ["shape.wdf", "0x38F2AA30"],
    "beaten": ["shape.wdf", "0xF7001687"],
    "defence": ["shape.wdf", "0x09F21394"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x92332ADC"]
  },
  "liumang": {
    "name": "流氓",
    "HP": 132,
    "MP": 0,
    "AP": 102,
    "SP": 12,
    "speed": 12,
    "growth": 1.042,
    "high_growth": 1.205,
    "title_level": 1,
    "skills": [],
    "gold": 40,
    "wood": 0,
    "soil": 60,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x996CD678"],
    "stand": ["shape.wdf", "0x8D052389"],
    "walk": ["shape.wdf", "0x32907688"],
    "hit": ["shape.wdf", "0x9E8D1971"],
    "beaten": ["shape.wdf", "0x701232A0"],
    "defence": ["shape.wdf", "0x061A19DD"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xB59A19B8"]
  },
  "yuguai": {
    "name": "鱼怪",
    "HP": 96,
    "MP": 96,
    "AP": 96,
    "SP": 110,
    "speed": 95,
    "growth": 1.152,
    "high_growth": 1.225,
    "title_level": 1,
    "skills": [[10, "yaozhimoli"]],
    "gold": 0,
    "wood": 25,
    "soil": 0,
    "water": 75,
    "fire": 0,
    "run": ["shape.wdf", "0x059919DC"],
    "stand": ["shape.wdf", "0xA94008FD"],
    "walk": ["shape.wdf", "0xA0F8A0DD"],
    "hit": ["shape.wdf", "0xF8A2C37A"],
    "beaten": ["shape.wdf", "0xFBC04019"],
    "defence": ["shape.wdf", "0xFD266883"],
    "magic": ["shape.wdf", "0xA9B9E763"],  # 4
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x77338BEE"]
  },
  "huayao": {
    "name": "花妖",
    "HP": 120,
    "MP": 0,
    "AP": 108,
    "SP": 12,
    "speed": 11,
    "growth": 1.058,
    "high_growth": 1.202,
    "title_level": 1,
    "skills": [],
    "gold": 0,
    "wood": 50,
    "soil": 50,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x87B556F2"],
    "stand": ["shape.wdf", "0x04890D49"],
    "walk": ["shape.wdf", "0x09C07E77"],
    "hit": ["shape.wdf", "0x82F8B86A"],
    "beaten": ["shape.wdf", "0x0C34D10D"],
    "defence": ["shape.wdf", "0x539ED20F"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xDE984023"]
  },
  "shibing": {
    "name": "士兵",
    "HP": 120,
    "MP": 0,
    "AP": 120,
    "SP": 6,
    "speed": 6,
    "growth": 1.06,
    "high_growth": 1.202,
    "title_level": 1,
    "skills": [],
    "gold": 50,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 50,
    "run": ["shape.wdf", "0x2372BF59"],
    "stand": ["shape.wdf", "0xA8756470"],
    "walk": ["shape.wdf", "0xA260CA8C"],
    "hit": ["shape.wdf", "0x98D7F621"],
    "beaten": ["shape.wdf", "0x3A42F93B"],
    "defence": ["shape.wdf", "0xADB19915"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "yayi": {
    "name": "衙役",
    "HP": 108,
    "MP": 0,
    "AP": 108,
    "SP": 12,
    "speed": 11,
    "growth": 1.05,
    "high_growth": 1.203,
    "title_level": 1,
    "skills": [],
    "gold": 0,
    "wood": 50,
    "soil": 0,
    "water": 0,
    "fire": 50,
    "run": ["shape.wdf", "0x477C6C31"],
    "stand": ["shape.wdf", "0x26F7F3E1"],
    "walk": ["shape.wdf", "0x3935CD44"],
    "hit": ["shape.wdf", "0xB0202D02"],
    "beaten": ["shape.wdf", "0x61FC976E"],
    "defence": ["shape.wdf", "0x59925669"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xB3084DB8"]
  },
  "nvzei": {
    "name": "女贼",
    "HP": 108,
    "MP": 0,
    "AP": 96,
    "SP": 31,
    "speed": 29,
    "growth": 1.065,
    "high_growth": 1.202,
    "title_level": 1,
    "skills": [],
    "gold": 50,
    "wood": 0,
    "soil": 0,
    "water": 50,
    "fire": 0,
    "jag": ["shape.wdf", "0x4EDB9899"],
    "run": ["shape.wdf", "0x56A96036"],
    "stand": ["shape.wdf", "0xAD0491D7"],
    "stand_normal": ["shape.wdf", "0x3D46505C"],
    "move": ["shape.wdf", "0x1FBCFBEA"],
    "walk": ["shape.wdf", "0x62AA4BE1"],
    "hit": ["shape.wdf", "0x2A44E34D"],
    "beaten": ["shape.wdf", "0x83A877F7"],
    "defence": ["shape.wdf", "0xE0F602EC"],
    "magic": ["shape.wdf", "0x27DCD80C"],
    "beaten_down": ["shape.wdf", "0xD08E3166"],
    "static": ["", "0x"]
  },
  "hulijing": {
    "name": "狐狸精",
    "HP": 120,
    "MP": 0,
    "AP": 132,
    "SP": 25,
    "speed": 23,
    "growth": 1.071,
    "high_growth": 1.202,
    "title_level": 2,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 65,
    "water": 0,
    "fire": 35,
    "run": ["shape.wdf", "0x6BF01E6D"],
    "stand": ["shape.wdf", "0xAE50B433"],
    "walk": ["shape.wdf", "0x106839A5"],
    "hit": ["shape.wdf", "0xB4E430EF"],
    "beaten": ["shape.wdf", "0x70760D7C"],
    "defence": ["shape.wdf", "0xC6D7CC10"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xF20F8357"]
  },
  "dufeng": {
    "name": "毒蜂",
    "HP": 72,
    "MP": 0,
    "AP": 144,
    "SP": 63,
    "speed": 60,
    "growth": 1.05,
    "high_growth": 1.203,
    "title_level": 2,
    "skills": [],
    "gold": 0,
    "wood": 70,
    "soil": 0,
    "water": 0,
    "fire": 30,
    "run": ["shape.wdf", "0xABB0F85E"],
    "stand": ["shape.wdf", "0xE37D1868"],  # 1435
    "walk": ["shape.wdf", "0xE7CF4AE4"],
    "hit": ["shape.wdf", "0x6DED4692"],
    "beaten": ["shape.wdf", "0x96819157"],
    "defence": ["shape.wdf", "0x88EA2E9A"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xA9AD0013"]
  },
  "nvyao": {
    "name": "女妖",
    "HP": 120,
    "MP": 0,
    "AP": 120,
    "SP": 12,
    "speed": 11,
    "growth": 1.055,
    "high_growth": 1.203,
    "title_level": 2,
    "skills": [],
    "gold": 50,
    "wood": 0,
    "soil": 0,
    "water": 50,
    "fire": 0,
    "run": ["shape.wdf", "0x9728FBCD"], 
    "jag": ["shape.wdf", "0xFC70AC0B"],
    "stand": ["shape.wdf", "0x688DD004"],
    "stand_normal": ["shape.wdf", "0x5DAD549B"],
    "move": ["shape.wdf", "0x481D1E5D"],
    "walk": ["shape.wdf", "0x2FEF7615"],
    "hit": ["shape.wdf", "0x3A696908"],
    "beaten": ["shape.wdf", "0x14EFDFC9"],
    "defence": ["shape.wdf", "0xDA0F8408"],
    "magic": ["shape.wdf", "0x8260E356"],
    "beaten_down": ["shape.wdf", "0x0C5137A5"],
    "static": ["", "0x"]
  },
  "shanzei": {
    "name": "山贼",
    "HP": 120,
    "MP": 0,
    "AP": 144,
    "SP": 12,
    "speed": 11,
    "growth": 1.045,
    "high_growth": 1.204,
    "title_level": 2,
    "skills": [],
    "gold": 45,
    "wood": 0,
    "soil": 55,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xE10904E5"],
    "stand": ["shape.wdf", "0x38F4DC8E"],
    "walk": ["shape.wdf", "0xAEF0806F"],
    "hit": ["shape.wdf", "0x85C0B736"],
    "beaten": ["shape.wdf", "0x0FC45589"],
    "defence": ["shape.wdf", "0x5A0B27DE"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xE8A7D963"]
  },
  "xiaolongnv": {
    "name": "小龙女",
    "HP": 84,
    "MP": 96,
    "AP": 84,
    "SP": 38,
    "speed": 36,
    "growth": 1.06,
    "high_growth": 1.202,
    "title_level": 2,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 95,
    "fire": 5,
    "run": ["shape.wdf", "0x8303559D"],
    "stand": ["shape.wdf", "0x98FEED1F"],
    "walk": ["shape.wdf", "0x993C5C2C"],
    "hit": ["shape.wdf", "0xA82A5097"],
    "beaten": ["shape.wdf", "0x89D04FDB"],
    "defence": ["shape.wdf", "0x36D24BDA"],
    "magic": ["shape.wdf", "0xF704761A"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x6821177C"]
  },
  "kulouguai": {
    "name": "骷髅怪",
    "HP": 84,
    "MP": 0,
    "AP": 144,
    "SP": 25,
    "speed": 24,
    "growth": 1.05,
    "high_growth": 1.203,
    "title_level": 2,
    "skills": [],
    "gold": 35,
    "wood": 0,
    "soil": 75,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x1836A046"],
    "stand": ["shape.wdf", "0x0E8F0D46"],
    "walk": ["shape.wdf", "0x15CD81CA"],
    "hit": ["shape.wdf", "0x9364D8B3"],  # 948
    "beaten": ["shape.wdf", "0x8B36F832"],
    "defence": ["shape.wdf", "0x9CC5A01C"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x780D4A9C"]
  },
  "jijing": {
    "name": "鸡精",
    "HP": 96,
    "MP": 0,
    "AP": 120,
    "SP": 31,
    "speed": 30,
    "growth": 1.05,
    "high_growth": 1.203,
    "title_level": 2,
    "skills": [],
    "gold": 0,
    "wood": 45,
    "soil": 55,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xE21F96D1"],
    "jag": ["shape.wdf", "0x3FC3319A"],
    "stand_normal": ["shape.wdf", "0x3E2E8B83"],
    "stand": ["shape.wdf", "0xCD9D7671"],
    "move": ["shape.wdf", "0xF63FDBF2"],
    "walk": ["shape.wdf", "0x6EC8DF52"],
    "hit": ["shape.wdf", "0x9EF0F27B"],
    "beaten": ["shape.wdf", "0x4A68F4C0"],
    "defence": ["shape.wdf", "0x7CFD46DC"],
    "magic": ["shape.wdf", "0x7ED0FDAC"],
    "beaten_down": ["shape.wdf", "0x989C3F24"],
    "static": ["", "0x"],
  },
  "qiannianlaoyao": {
    "name": "千年老妖",
    "HP": 144,
    "MP": 96,
    "AP": 42,
    "SP": 0,
    "speed": 0,
    "growth": 1.142,
    "high_growth": 1.221,
    "title_level": 2,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 60,
    "water": 0,
    "fire": 40,
    "run": ["shape.wdf", "0x260CDA87"],
    "stand": ["shape.wdf", "0xE567D488"],
    "walk": ["shape.wdf", "0x1679382A"],
    "hit": ["shape.wdf", "0x388A4093"],
    "beaten": ["shape.wdf", "0xD0C5FFC8"],
    "defence": ["shape.wdf", "0x28365622"],
    "magic": ["shape.wdf", "0x1E4B0077"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x759DB60F"]
  },
  "zhanshennvwa": {
    "name": "战神女娲",
    "HP": 84,
    "MP": 84,
    "AP": 84,
    "SP": 84,
    "speed": 72,
    "growth": 1.173,
    "high_growth": 1.236,
    "title_level": 3,
    "skills": [],
    "gold": 10,
    "wood": 90,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x68C2EADF"],  # 680
    "stand": ["shape.wdf", "0xF43E4F12"],
    "walk": ["shape.wdf", "0x5461D47D"],
    "hit": ["shape.wdf", "0xE2066294"],
    "beaten": ["shape.wdf", "0x5BF3B0CE"],
    "defence": ["shape.wdf", "0xD93306AD"],
    "magic": ["shape.wdf", "0x51EB457A"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x2EBA0B85"]
  },
  "eyu": {
    "name": "鳄鱼",
    "HP": 144,
    "MP": 0,
    "AP": 120,
    "SP": 19,
    "speed": 18,
    "growth": 1.071,
    "high_growth": 1.202,
    "title_level": 3,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 55,
    "water": 45,
    "fire": 0,
    "run": ["shape.wdf", "0x583C51F1"],
    "stand": ["shape.wdf", "0x186A43E9"],
    "walk": ["shape.wdf", "0xA09FA982"],  # 1029
    "hit": ["shape.wdf", "0x10D23AFA"],
    "beaten": ["shape.wdf", "0x60B693AB"],  # 633
    "defence": ["shape.wdf", "0x0DFB1D14"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x3213A07E"]
  },
  "shizi": {
    "name": "狮子",
    "HP": 120,
    "MP": 0,
    "AP": 114,
    "SP": 19,
    "speed": 18,
    "growth": 1.06,
    "high_growth": 1.202,
    "title_level": 3,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 40,
    "water": 0,
    "fire": 60,
    "run": ["shape.wdf", "0xCDA62DBA"],
    "stand": ["shape.wdf", "0x5B2AD6CB"],
    "walk": ["shape.wdf", "0x8A05EDF0"],
    "hit": ["shape.wdf", "0x78B208A1"],
    "beaten": ["shape.wdf", "0xF59C9968"],
    "defence": ["shape.wdf", "0x1D56E01A"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x4D41D5D2"]
  },
  "daxiang": {
    "name": "大象",
    "HP": 168,
    "MP": 0,
    "AP": 108,
    "SP": -32,
    "speed": -29,
    "growth": 1.091,
    "high_growth": 1.204,
    "title_level": 3,
    "skills": [],
    "gold": 0,
    "wood": 35,
    "soil": 65,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x3E20CC08"],  # 406
    "stand": ["shape.wdf", "0x618E10B0"],
    "walk": ["shape.wdf", "0xE1E4E409"],
    "hit": ["shape.wdf", "0x98D77093"],
    "beaten": ["shape.wdf", "0x2C707784"],
    "defence": ["shape.wdf", "0x1BE201F8"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x1108DE67"]
  },
  "dapeng": {
    "name": "大鹏",
    "HP": 96,
    "MP": 0,
    "AP": 138,
    "SP": 63,
    "speed": 59,
    "growth": 1.06,
    "high_growth": 1.202,
    "title_level": 3,
    "skills": [],
    "gold": 60,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 40,
    "run": ["shape.wdf", "0x5CB8437B"],
    "jag": ["shape.wdf", "0x101A2A16"],
    "stand": ["shape.wdf", "0xAE8E048F"],
    "stand_normal": ["shape.wdf", "0x82A55C83"],
    "move": ["shape.wdf", "0xE2979F4F"],
    "walk": ["shape.wdf", "0xBFECF819"],
    "hit": ["shape.wdf", "0xD163F10A"],
    "beaten": ["shape.wdf", "0x96C1B363"],
    "defence": ["shape.wdf", "0x4D6C7DA4"],
    "magic": ["shape.wdf", "0x749ADF96"],
    "beaten_down": ["shape.wdf", "0x42D246FE"],
    "static": ["", "0x"],
  },
  "laohu": {
    "name": "老虎",  # 9A17F3E3
    "HP": 120,
    "MP": 0,
    "AP": 120,
    "SP": 25,
    "speed": 23,
    "growth": 1.081,
    "high_growth": 1.203,
    "title_level": 3,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 50,
    "water": 0,
    "fire": 50,
    "run": ["shape.wdf", "0x61FEF2A5"],
    "jag": ["shape.wdf", "0xF735C9A9"],
    "stand_normal": ["shape.wdf", "0x21CE1B76"],
    "stand": ["shape.wdf", "0x4D623B90"], 
    "move": ["shape.wdf", "0x7521B4BF"],  
    "walk": ["shape.wdf", "0x8D53D7DD"],
    "hit": ["shape.wdf", "0x129FA3B0"],
    "beaten": ["shape.wdf", "0x76E60111"],
    "defence": ["", "0x"],
    "magic": ["shape.wdf", "0x24DA5D75"],
    "beaten_down": ["shape.wdf", "0x8FDAD586"],
    "static": ["", "0x"]
  },
  "qiangdao": {
    "name": "强盗",
    "HP": 120,
    "MP": 0,
    "AP": 96,
    "SP": 25,
    "speed": 24,
    "growth": 1.06,
    "high_growth": 1.202,
    "title_level": 3,
    "skills": [],
    "gold": 45,
    "wood": 0,
    "soil": 55,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x9248C90A"],
    "stand": ["shape.wdf", "0xA8BFB73B"],
    "walk": ["shape.wdf", "0xFD851096"],
    "hit": ["shape.wdf", "0xF26D871D"],
    "beaten": ["shape.wdf", "0x593AE526"],
    "defence": ["shape.wdf", "0x8A23ACE1"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x4E1EC463"]
  },
  "heixiong": {
    "name": "黑熊",
    "HP": 132,
    "MP": 0,
    "AP": 120,
    "SP": -25,
    "speed": -23,
    "growth": 1.071,
    "high_growth": 1.231,
    "title_level": 3,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 40,
    "water": 0,
    "fire": 60,
    "run": ["shape.wdf", "0x9370F9D3"],
    "stand": ["shape.wdf", "0x162C22C9"],
    "walk": ["shape.wdf", "0x58AA587E"],
    "hit": ["shape.wdf", "0x155EB9F4"],
    "beaten": ["shape.wdf", "0xD70C8074"],
    "defence": ["shape.wdf", "0x65B88023"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x3CEC1591"]
  },
  "shuyao": {
    "name": "树妖",
    "HP": 144,
    "MP": 0,
    "AP": 96,
    "SP": 0,
    "speed": 0,
    "growth": 1.076,
    "high_growth": 1.202,
    "title_level": 3,
    "skills": [],
    "gold": 10,
    "wood": 90,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x25AF6E73"],
    "stand": ["shape.wdf", "0x6C723D69"],
    "walk": ["shape.wdf", "0x3ED84216"],
    "hit": ["shape.wdf", "0x7C76C905"],
    "beaten": ["shape.wdf", "0x4B2CACB9"],
    "defence": ["shape.wdf", "0xB53BD551"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x21E267D5"]
  },
  "hamajing": {
    "name": "蛤蟆精",
    "HP": 132,
    "MP": 0,
    "AP": 102,
    "SP": -13,
    "speed": -12,
    "growth": 1.086,
    "high_growth": 1.204,
    "title_level": 4,
    "skills": [],
    "gold": 30,
    "wood": 0,
    "soil": 70,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x4983D129"],
    "stand": ["shape.wdf", "0x1122C6D2"],
    "walk": ["shape.wdf", "0x81D749BE"],
    "hit": ["shape.wdf", "0x42D2F569"],
    "beaten": ["shape.wdf", "0x8FC9CB38"],
    "defence": ["shape.wdf", "0x2A6693A5"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xDF976C1E"]
  },
  "xiabing": {
    "name": "虾兵",
    "HP": 156,
    "MP": 0,
    "AP": 108,
    "SP": 12,
    "speed": 11,
    "growth": 1.071,
    "high_growth": 1.202,
    "title_level": 4,
    "skills": [],
    "gold": 0,
    "wood": 25,
    "soil": 0,
    "water": 75,
    "fire": 0,
    "run": ["shape.wdf", "0xC6808FEC"],
    "stand": ["shape.wdf", "0x70A7F1CD"],
    "walk": ["shape.wdf", "0x2A203B1F"],
    "hit": ["shape.wdf", "0x1F28A466"],
    "beaten": ["shape.wdf", "0x6926B8F8"],
    "defence": ["shape.wdf", "0x7EA8FA68"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xDB68BB03"]
  },
  "xiejiang": {
    "name": "蟹将",
    "HP": 144,
    "MP": 0,
    "AP": 114,
    "SP": 12,
    "speed": 11,
    "growth": 1.071,
    "high_growth": 1.202,
    "title_level": 4,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 20,
    "water": 80,
    "fire": 0,
    "run": ["shape.wdf", "0xDB1716B1"],
    "stand": ["shape.wdf", "0x70A812E1"],
    "walk": ["shape.wdf", "0x3E952AAA"],
    "hit": ["shape.wdf", "0x78846A4D"],
    "beaten": ["shape.wdf", "0xFFD5F67A"],
    "defence": ["shape.wdf", "0x94A5917C"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x60888D2F"]
  },
  "dashou": {
    "name": "打手",
    "HP": 108,
    "MP": 0,
    "AP": 156,
    "SP": 24,
    "speed": 24,
    "growth": 1.071,
    "high_growth": 1.202,
    "title_level": 4,
    "skills": [],
    "gold": 50,
    "wood": 50,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x5F8E0067"],
    "stand": ["shape.wdf", "0x8A51A71D"],
    "walk": ["shape.wdf", "0xC7F51159"],
    "hit": ["shape.wdf", "0xEC6F79F4"],
    "beaten": ["shape.wdf", "0x54C4481A"],
    "defence": ["shape.wdf", "0x7B9277F9"],
    "magic": ["shape.wdf", "0x799965C4"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x3F6E1130"]
  },
  "guichengxiang": {
    "name": "龟丞相",
    "HP": 180,
    "MP": 72,
    "AP": 36,
    "SP": -107,
    "speed": -96,
    "growth": 1.116,
    "high_growth": 1.211,
    "title_level": 4,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 15,
    "water": 85,
    "fire": 0,
    "run": ["shape.wdf", "0x124DBF4B"],
    "stand": ["shape.wdf", "0xB0E6B931"],
    "walk": ["shape.wdf", "0x53BB423C"],
    "hit": ["shape.wdf", "0xACBDB9E5"],
    "beaten": ["shape.wdf", "0x19953EFC"],
    "defence": ["shape.wdf", "0x6DCF1F37"],
    "magic": ["shape.wdf", "0xD3B754A3"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x51C20B00"]
  },
  "heixiongjing": {
    "name": "黑熊精",
    "HP": 144,
    "MP": 0,
    "AP": 144,
    "SP": -39,
    "speed": -36,
    "growth": 1.096,
    "high_growth": 1.205,
    "title_level": 4,
    "skills": [],
    "gold": 60,
    "wood": 0,
    "soil": 40,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xE490BFA3"],
    "stand": ["shape.wdf", "0x36A05574"],
    "walk": ["shape.wdf", "0x91E7D789"],
    "hit": ["shape.wdf", "0x32B2BAE6"],
    "beaten": ["shape.wdf", "0xFB40C501"],
    "defence": ["shape.wdf", "0x18A8B240"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x578A6F8A"]
  },
  "shuiyao": {
    "name": "水妖",
    "HP": 120,
    "MP": 0,
    "AP": 120,
    "SP": 39,
    "speed": 35,
    "growth": 1.106,
    "high_growth": 1.208,
    "title_level": 4,
    "skills": [],
    "gold": 30,
    "wood": 0,
    "soil": 0,
    "water": 70,
    "fire": 0,
    "run": ["shape.wdf", "0xD7505720"],
    "stand": ["shape.wdf", "0xCEC9319C"],
    "walk": ["shape.wdf", "0x839870CC"],
    "hit": ["shape.wdf", "0xDEA8818C"],
    "beaten": ["shape.wdf", "0x54803D2E"],
    "defence": ["shape.wdf", "0xFC590C8D"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xAAD2CC09"]
  },
  "fuhuonvwa": {
    "name": "复活女娲",
    "HP": 60,
    "MP": 280,
    "AP": 40,
    "SP": 50,
    "speed": 37,
    "growth": 1.35,
    "high_growth": 1.225,
    "title_level": 5,
    "skills": [],
    "gold": 75,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 25,
    "run": ["shape.wdf", "0x4F89441E"],
    "stand": ["shape.wdf", "0x5D7B6B46"],
    "walk": ["shape.wdf", "0x88CA649C"],
    "hit": ["shape.wdf", "0x0EA4D20F"],
    "beaten": ["shape.wdf", "0xE59A8113"],
    "defence": ["shape.wdf", "0xE17C5C52"],
    "magic": ["shape.wdf", "0x7E640A31"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x2FFD368C"]
  },
  "wutougui": {
    "name": "无头鬼",
    "HP": 108,
    "MP": 0,
    "AP": 132,
    "SP": 12,
    "speed": 11,
    "growth": 1.081,
    "high_growth": 1.203,
    "title_level": 5,
    "skills": [],
    "gold": 0,
    "wood": 30,
    "soil": 70,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x799B1E3C"],
    "stand": ["shape.wdf", "0xBACADC2E"],
    "walk": ["shape.wdf", "0xAC24B545"],
    "hit": ["shape.wdf", "0x0C49DE32"],
    "beaten": ["shape.wdf", "0xDD820CF0"],
    "defence": ["shape.wdf", "0x2B213D4E"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xC748867C"]
  },
  "wushengui": {
    "name": "无身鬼",
    "HP": 96,
    "MP": 0,
    "AP": 144,
    "SP": 13,
    "speed": 12,
    "growth": 1.091,
    "high_growth": 1.204,
    "title_level": 5,
    "skills": [],
    "gold": 0,
    "wood": 40,
    "soil": 60,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xC631BB84"],
    "stand": ["shape.wdf", "0xBE899C52"],
    "walk": ["shape.wdf", "0xA4BB9979"],
    "hit": ["shape.wdf", "0x9F3DF0E6"],
    "beaten": ["shape.wdf", "0x983B29D6"],  # 976
    "defence": ["shape.wdf", "0x2DB26823"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "xixuegui": {
    "name": "吸血鬼",
    "HP": 72,
    "MP": 0,
    "AP": 168,
    "SP": 13,
    "speed": 11,
    "growth": 1.142,
    "high_growth": 1.221,
    "title_level": 5,
    "skills": [],
    "gold": 25,
    "wood": 0,
    "soil": 75,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xF10437EF"],
    "stand": ["shape.wdf", "0x667F092B"],
    "walk": ["shape.wdf", "0xA85229D6"],
    "hit": ["shape.wdf", "0xB19A5456"],
    "beaten": ["", "0x"],
    "defence": ["shape.wdf", "0x2B2F7789"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x2559F102"]
  },
  "yegui": {
    "name": "野鬼",
    "HP": 84,
    "MP": 0,
    "AP": 156,
    "SP": 13,
    "speed": 12,
    "growth": 1.086,
    "high_growth": 1.204,
    "title_level": 5,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 70,
    "water": 0,
    "fire": 30,
    "run": ["shape.wdf", "0x2B0478C7"],  # 655
    "stand": ["shape.wdf", "0x4ABBFBD5"],
    "walk": ["shape.wdf", "0x6579BFB5"],
    "hit": ["shape.wdf", "0xC1B24BAC"],
    "beaten": ["shape.wdf", "0x2A479CCC"],
    "defence": ["shape.wdf", "0x8754CB1D"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xD117595B"]
  },
  "yuanhun": {
    "name": "冤魂",
    "HP": 84,
    "MP": 0,
    "AP": 150,
    "SP": 13,
    "speed": 12,
    "growth": 1.111,
    "high_growth": 1.209,
    "title_level": 5,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 65,
    "water": 35,
    "fire": 0,
    "run": ["shape.wdf", "0x844BC66B"],
    "stand": ["shape.wdf", "0x29221139"],
    "walk": ["shape.wdf", "0xABEBBD99"],
    "hit": ["shape.wdf", "0xDAFF18F4"],  # 
    "beaten": ["shape.wdf", "0x56733013"],
    "defence": ["shape.wdf", "0x45A40E19"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x39FD22ED"]
  },
  "guhun": {
    "name": "孤魂",
    "HP": 96,
    "MP": 0,
    "AP": 162,
    "SP": 13,
    "speed": 12,
    "growth": 1.106,
    "high_growth": 1.208,
    "title_level": 5,
    "skills": [],
    "gold": 0,
    "wood": 35,
    "soil": 65,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xC56DDF51"],
    "stand": ["shape.wdf", "0x133FE4BC"],
    "walk": ["shape.wdf", "0x87D5CA4D"],
    "hit": ["shape.wdf", "0xF9321464"],
    "beaten": ["shape.wdf", "0x178626C1"],
    "defence": ["shape.wdf", "0x2FB5322A"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x76A5ABFD"]
  },
  "youling": {
    "name": "幽灵",
    "HP": 84,
    "MP": 0,
    "AP": 138,
    "SP": 14,
    "speed": 12,
    "growth": 1.173,
    "high_growth": 1.236,
    "title_level": 5,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 60,
    "water": 40,
    "fire": 0,
    "run": ["shape.wdf", "0x66701859"],
    "stand": ["shape.wdf", "0x6E041547"],
    "walk": ["shape.wdf", "0xDD52C93A"],
    "hit": ["shape.wdf", "0x3095AC63"],
    "beaten": ["shape.wdf", "0xC87B8D00"],
    "defence": ["shape.wdf", "0x683DDDAE"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x5B9D0DCC"]
  },
  "xiuluo": {
    "name": "修罗",
    "HP": 108,
    "MP": 0,
    "AP": 174,
    "SP": 13,
    "speed": 12,
    "growth": 1.101,
    "high_growth": 1.207,
    "title_level": 5,
    "skills": [],
    "gold": 50,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 50,
    "run": ["shape.wdf", "0x925D4644"],
    "stand": ["shape.wdf", "0xC7EAC3F1"],
    "walk": ["shape.wdf", "0xD719314F"],
    "hit": ["shape.wdf", "0xEBE564E7"],
    "beaten": ["shape.wdf", "0xBF82889B"],
    "defence": ["shape.wdf", "0xB7E3B65C"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x5DC917BD"]
  },
  "fuzhounvwa": {
    "name": "符咒女娲",
    "HP": 90,
    "MP": 50,
    "AP": 20,
    "SP": 120,
    "speed": 88,
    "growth": 1.35,
    "high_growth": 1.221,
    "title_level": 6,
    "skills": [],
    "gold": 0,
    "wood": 25,
    "soil": 75,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x7D5BFFBC"],
    "stand": ["shape.wdf", "0x78DCC359"],
    "walk": ["shape.wdf", "0xE1E89EB6"],
    "hit": ["shape.wdf", "0xDB4600C4"],
    "beaten": ["shape.wdf", "0x9E1D2BAD"],
    "defence": ["shape.wdf", "0xF45ED5CE"],
    "magic": ["shape.wdf", "0xCFE04A15"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x98ACB22A"]
  },
  "bingxiong": {
    "name": "冰熊",
    "HP": 144,
    "MP": 0,
    "AP": 96,
    "SP": -26,
    "speed": -24,
    "growth": 1.091,
    "high_growth": 1.204,
    "title_level": 6,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 60,
    "water": 40,
    "fire": 0,
    "run": ["shape.wdf", "0xCCDAD36E"],
    "stand": ["shape.wdf", "0x983DDCC3"],
    "walk": ["shape.wdf", "0x41D12500"],
    "hit": ["shape.wdf", "0x881F5EB3"],
    "beaten": ["shape.wdf", "0xE08BBB1A"],
    "defence": ["shape.wdf", "0x1AEAF718"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x24F343D2"]
  },
  "baihu": {
    "name": "白虎",
    "HP": 120,
    "MP": 0,
    "AP": 120,
    "SP": 14,
    "speed": 12,
    "growth": 1.188,
    "high_growth": 1.245,
    "title_level": 6,
    "skills": [],
    "gold": 60,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 40,
    "run": ["shape.wdf", "0x5FB28D8F"],
    "jag": ["shape.wdf", "0xB763B8EE"],
    "stand": ["shape.wdf", "0x638BFDDB"],
    "move": ["shape.wdf", "0x2C1E7693"],
    "walk": ["shape.wdf", "0x2D8893D1"],
    "hit": ["shape.wdf", "0xE513139F"],  # 1447
    "beaten": ["shape.wdf", "0x884B84CA"],
    "defence": ["shape.wdf", "0xC5C3FCC4"],
    "magic": ["shape.wdf", "0xB70488BD"],
    "beaten_down": ["shape.wdf", "0x9648321B"],
    "static": ["", "0x"],
  },
  "liangjiaoguai": {
    "name": "两角怪",
    "HP": 132,
    "MP": 0,
    "AP": 108,
    "SP": 6,
    "speed": 6,
    "growth": 1.071,
    "high_growth": 1.202,
    "title_level": 6,
    "skills": [],
    "gold": 50,
    "wood": 0,
    "soil": 50,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xB1DC4808"],
    "stand": ["shape.wdf", "0x44EC0815"],
    "walk": ["shape.wdf", "0xBEDF2993"],
    "hit": ["shape.wdf", "0xBB54B60C"],
    "beaten": ["shape.wdf", "0xE6F0D923"],
    "defence": ["shape.wdf", "0xAC4A5F56"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x57A29CC1"]
  },
  "sanweiguai": {
    "name": "三尾怪",
    "HP": 156,
    "MP": 0,
    "AP": 90,
    "SP": 19,
    "speed": 18,
    "growth": 1.081,
    "high_growth": 1.203,
    "title_level": 7,
    "skills": [],
    "gold": 0,
    "wood": 65,
    "soil": 35,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xA780C730"],
    "stand": ["shape.wdf", "0xF7937617"],
    "walk": ["shape.wdf", "0x216B2745"],
    "hit": ["shape.wdf", "0x90E04F21"],
    "beaten": ["shape.wdf", "0x921C71C7"],
    "defence": ["shape.wdf", "0x1C8026A4"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x17C37276"]
  },
  "zhizhujing": {
    "name": "蜘蛛精",
    "HP": 96,
    "MP": 120,
    "AP": 48,
    "SP": 26,
    "speed": 24,
    "growth": 1.086,
    "high_growth": 1.204,
    "title_level": 7,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 60,
    "water": 40,
    "fire": 0,
    "run": ["shape.wdf", "0xB7857B43"],
    "stand": ["shape.wdf", "0xECBF1A3D"],
    "walk": ["shape.wdf", "0x1D855A0D"],  # 1179
    "hit": ["shape.wdf", "0x1B7B7194"],
    "beaten": ["shape.wdf", "0x295D6DC9"],
    "defence": ["shape.wdf", "0x86E1FD99"],
    "magic": ["shape.wdf", "0x32201898"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x74606705"]
  },
  "chongchongchong": {
    "name": "冲冲虫",
    "HP": 120,
    "MP": 96,
    "AP": 30,
    "SP": 100,
    "speed": 84,
    "growth": 1.193,
    "high_growth": 1.248,
    "title_level": 7,
    "skills": [[10, "hongxiutianxiang"],[30, "lianbuqingwu"],[50, "chuchukelian"],[70, "moshenhuti"]],
    "gold": 30,
    "wood": 0,
    "soil": 70,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xAD31E1EA"],
    "stand": ["shape.wdf", "0xC463B972"],
    "walk": ["shape.wdf", "0xC3C3CE08"],
    "hit": ["shape.wdf", "0x812BC457"],
    "beaten": ["shape.wdf", "0xC27E40BA"],
    "defence": ["shape.wdf", "0x7B14D8E7"],
    "magic": ["shape.wdf", "0x06C69364"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x574EEAB7"]
  },
  "niaozuishou": {
    "name": "鸟嘴兽",
    "HP": 132,
    "MP": 0,
    "AP": 108,
    "SP": -13,
    "speed": -12,
    "growth": 1.096,
    "high_growth": 1.205,
    "title_level": 7,
    "skills": [],
    "gold": 60,
    "wood": 0,
    "soil": 40,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x91DA849E"],
    "jag": ["shape.wdf", "0x29D94F5D"],
    "stand_normal": ["shape.wdf", "0x1A2FC2ED"],
    "stand": ["shape.wdf", "0x94404BC3"],
    "move": ["shape.wdf", "0x8154595B"],
    "walk": ["shape.wdf", "0x9587631F"],
    "hit": ["shape.wdf", "0x5B574112"],
    "beaten": ["shape.wdf", "0x5F2F7ECE"],  
    "defence": ["shape.wdf", "0x0E23673C"],
    "magic": ["shape.wdf", "0x29A51548"],
    "beaten_down": ["shape.wdf", "0xF32E07A3"],
    "static": ["", "0x"]
  },
  "jingguai": {
    "name": "精怪",
    "HP": 96,
    "MP": 0,
    "AP": 144,
    "SP": 0,
    "speed": 0,
    "growth": 1.086,
    "high_growth": 1.204,
    "title_level": 7,
    "skills": [],
    "gold": 80,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 20,
    "run": ["shape.wdf", "0x2ED36E11"],
    "stand": ["shape.wdf", "0xF69A1184"],
    "walk": ["shape.wdf", "0x11BE9AEF"],
    "hit": ["shape.wdf", "0xD4B8C139"],
    "beaten": ["shape.wdf", "0x749CA3E4"],
    "defence": ["shape.wdf", "0x28AE6BC6"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xD01C7435"]
  },
  "shanyao": {
    "name": "山妖",
    "HP": 108,
    "MP": 0,
    "AP": 132,
    "SP": 13,
    "speed": 12,
    "growth": 1.091,
    "high_growth": 1.204,
    "title_level": 7,
    "skills": [],
    "gold": 30,
    "wood": 0,
    "soil": 70,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x6079BA0E"],
    "stand": ["shape.wdf", "0x673536B9"],
    "walk": ["shape.wdf", "0x5FC93B35"],
    "hit": ["shape.wdf", "0xA5546EED"],
    "beaten": ["shape.wdf", "0x1C3D901F"],
    "defence": ["shape.wdf", "0x2A7D82CB"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xBCAF903C"],
  },
  "hudiexianzi": {
    "name": "蝴蝶仙子",
    "HP": 96,
    "MP": 0,
    "AP": 96,
    "SP": 90,
    "speed": 83,
    "growth": 1.081,
    "high_growth": 1.203,
    "title_level": 7,
    "skills": [],
    "gold": 0,
    "wood": 60,
    "soil": 0,
    "water": 40,
    "fire": 0,
    "run": ["shape.wdf", "0x2EF33B06"],
    "stand": ["shape.wdf", "0x3828779E"],
    "stand_normal": ["shape.wdf", "0x316273BC"],  # 336
    "walk": ["shape.wdf", "0x891002F9"],
    "hit": ["shape.wdf", "0xE432C378"],
    "beaten": ["shape.wdf", "0x3A071AEE"],
    "defence": ["shape.wdf", "0xD5D3DBA9"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xD72C8A4B"]
  },
  "gudairuishou": {
    "name": "古代瑞兽",
    "HP": 84,
    "MP": 180,
    "AP": 36,
    "SP": 0,
    "speed": 0,
    "growth": 1.203,
    "high_growth": 1.254,
    "title_level": 7,
    "skills": [],
    "gold": 65,
    "wood": 0,
    "soil": 35,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xCAAB76D5"],
    "stand": ["shape.wdf", "0xBBC78EF1"],  # 1203
    "walk": ["shape.wdf", "0x8BF68D5D"],
    "hit": ["shape.wdf", "0x9B35CE8D"],
    "beaten": ["shape.wdf", "0x5CF6B96E"],
    "defence": ["shape.wdf", "0xE383DE59"],
    "magic": ["shape.wdf", "0xC944B9F3"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xD9C108BF"]
  },
  "shuguai": {
    "name": "鼠怪",
    "HP": 96,
    "MP": 0,
    "AP": 144,
    "SP": 79,
    "speed": 71,
    "growth": 1.106,
    "high_growth": 1.208,
    "title_level": 7,
    "skills": [],
    "gold": 0,
    "wood": 60,
    "soil": 40,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0xD42B054A"],
    "jag": ["shape.wdf", "0x59C1F3F5"],
    "stand_normal": ["shape.wdf", "0x85D20F2E"],
    "stand": ["shape.wdf", "0x0F4E9E80"],
    "move": ["shape.wdf", "0xFF5A4EAA"],
    "walk": ["shape.wdf", "0x0DC1C46C"],
    "hit": ["shape.wdf", "0x92C5B61C"],
    "beaten": ["shape.wdf", "0x6BB301C5"],
    "defence": ["shape.wdf", "0x23076AEF"],
    "magic": ["shape.wdf", "0xDD86B4EC"],
    "beaten_down": ["shape.wdf", "0x723CEB57"],
    "static": ["", "0x"]
  },
  "leiniaoren": {
    "name": "雷鸟人",
    "HP": 120,
    "MP": 0,
    "AP": 144,
    "SP": 14,
    "speed": 12,
    "growth": 1.213,
    "high_growth": 1.26,
    "title_level": 7,
    "skills": [],
    "gold": 40,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 60,
    "run": ["shape.wdf", "0xD4B50A16"],
    "stand": ["shape.wdf", "0xA1463C24"],
    "walk": ["shape.wdf", "0x1BD4E973"],
    "hit": ["shape.wdf", "0x7F34308B"],
    "beaten": ["shape.wdf", "0x88F6B7E8"],
    "defence": ["shape.wdf", "0x9C7493B4"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x398BFB4F"]
  },
  "hangangguai": {
    "name": "寒钢怪",
    "HP": 66,
    "MP": 108,
    "AP": 48,
    "SP": 19,
    "speed": 17,
    "growth": 1.106,
    "high_growth": 1.208,
    "title_level": 7,
    "skills": [],
    "gold": 95,
    "wood": 0,
    "soil": 0,
    "water": 5,
    "fire": 0,
    "run": ["shape.wdf", "0xD21DE04A"],
    "stand": ["shape.wdf", "0x3B044F8F"],
    "walk": ["shape.wdf", "0x5A223551"],
    "hit": ["shape.wdf", "0xE97AC333"],
    "beaten": ["shape.wdf", "0x5BCADFD4"],
    "defence": ["shape.wdf", "0x30CA247F"],
    "magic": ["shape.wdf", "0xD8E9B5FE"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x56688360"]
  },
  "duyanjuren": {
    "name": "独眼巨人",
    "HP": 54,
    "MP": 96,
    "AP": 78,
    "SP": 26,
    "speed": 23,
    "growth": 1.116,
    "high_growth": 1.211,
    "title_level": 7,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 70,
    "water": 0,
    "fire": 30,
    "run": ["shape.wdf", "0x9C026687"],
    "stand": ["shape.wdf", "0x73EEA2A5"],
    "walk": ["shape.wdf", "0xF98BEFBD"],
    "hit": ["shape.wdf", "0x7D46BAFC"],
    "beaten": ["shape.wdf", "0x417163CD"],
    "defence": ["shape.wdf", "0x439C7952"],
    "magic": ["shape.wdf", "0x56F17261"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xED850381"]
  },
  "siling": {
    "name": "死灵",
    "HP": 120,
    "MP": 0,
    "AP": 162,
    "SP": 13,
    "speed": 12,
    "growth": 1.111,
    "high_growth": 1.209,
    "title_level": 7,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 70,
    "water": 30,
    "fire": 0,
    "run": ["shape.wdf", "0xD6CD4B82"],
    "stand": ["shape.wdf", "0x3964D90F"],
    "walk": ["shape.wdf", "0x8635AEFC"],
    "hit": ["shape.wdf", "0x513A980E"],
    "beaten": ["shape.wdf", "0x215E06CF"],
    "defence": ["shape.wdf", "0xB688C0FE"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x382CE7B1"]
  },
  "yemanwang": {
    "name": "野蛮王",
    "HP": 60,
    "MP": 108,
    "AP": 120,
    "SP": 19,
    "speed": 18,
    "growth": 1.101,
    "high_growth": 1.207,
    "title_level": 8,
    "skills": [],
    "gold": 0,
    "wood": 60,
    "soil": 0,
    "water": 40,
    "fire": 0,
    "run": ["shape.wdf", "0x540CDF7B"],
    "stand": ["shape.wdf", "0x725E4A5D"],
    "walk": ["shape.wdf", "0x9E3E30AD"],
    "hit": ["shape.wdf", "0xBB83B080"],
    "beaten": ["shape.wdf", "0x8B479AAE"],
    "defence": ["shape.wdf", "0xE74D58A9"],
    "magic": ["shape.wdf", "0x43B5B467"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x8A952E52"]
  },
  "huoshennvwa": {
    "name": "火神女娲",
    "HP": 10,
    "MP": 0,
    "AP": 350,
    "SP": 50,
    "speed": 37,
    "growth": 1.35,
    "high_growth": 1.254,
    "title_level": 8,
    "skills": [],
    "gold": 0,
    "wood": 15,
    "soil": 0,
    "water": 0,
    "fire": 85,
    "run": ["shape.wdf", "0x11C22974"],
    "stand": ["shape.wdf", "0x3FC46DA5"],
    "walk": ["shape.wdf", "0x4CA79471"],
    "hit": ["shape.wdf", "0xDD1F37DE"],
    "beaten": ["shape.wdf", "0x25F1298D"],
    "defence": ["shape.wdf", "0xF4B285BA"],
    "magic": ["shape.wdf", "0x98710501"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x4C47A689"]
  },
  "diyuzhanshen": {
    "name": "地狱战神",
    "HP": 96,
    "MP": 144,
    "AP": 36,
    "SP": -42,
    "speed": -36,
    "growth": 1.173,
    "high_growth": 1.236,
    "title_level": 8,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 50,
    "water": 50,
    "fire": 0,
    "run": ["shape.wdf", "0x7EF41CB0"],
    "stand": ["shape.wdf", "0x70F35D70"],
    "walk": ["shape.wdf", "0x7F8C00C3"],
    "hit": ["shape.wdf", "0x3D5634A3"],
    "beaten": ["shape.wdf", "0x5B13FA1C"],
    "defence": ["shape.wdf", "0x8F487B17"],
    "magic": ["shape.wdf", "0x1A6B6FFB"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x12807229"]
  },
  "jiaolong": {
    "name": "蛟龙",
    "HP": 48,
    "MP": 180,
    "AP": 60,
    "SP": 60,
    "speed": 48,
    "growth": 1.254,
    "high_growth": 1.289,
    "title_level": 8,
    "skills": [[10, "longjuanyuji"],[30, "longtengshuijian"],[50, "longxiaojiutian"],[70, "jiaolongchuhai"]],
    "gold": 5,
    "wood": 0,
    "soil": 0,
    "water": 95,
    "fire": 0,
    "run": ["shape.wdf", "0x6A7AC8FC"],
    "stand": ["shape.wdf", "0x370970EA"],
    "walk": ["shape.wdf", "0x1C37C867"],
    "hit": ["shape.wdf", "0xC10BC830"], 
    "beaten": ["shape.wdf", "0x5FE3F3C2"],
    "defence": ["shape.wdf", "0x213AE16A"],
    "magic": ["shape.wdf", "0x110070C0"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x034598C3"]
  },
  "fenghuang": {
    "name": "凤凰",
    "HP": 36,
    "MP": 180,
    "AP": 48,
    "SP": 76,
    "speed": 60,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 8,
    "skills": [[10, "diyuliehuo"],[30, "tianleinuhuo"],[50, "sanweizhenhuo"],[70, "liehuojiaoyang"]],
    "gold": 0,
    "wood": 0,
    "soil": 5,
    "water": 0,
    "fire": 95,
    "run": ["shape.wdf", "0x22883068"],
    "stand": ["shape.wdf", "0x2DD87623"],  # A9027E94   ADA513D4
    "stand_normal": ["shape.wdf", "0xA9027E94"], 
    "walk": ["shape.wdf", "0x6C1BB09D"],
    "hit": ["shape.wdf", "0x6B914BF3"],
    "beaten": ["shape.wdf", "0xA3DA2B3C"],
    "defence": ["shape.wdf", "0xADA513D4"],  # 遗留
    "magic": ["shape.wdf", "0x0B5E6653"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "houjing": {
    "name": "猴精",
    "HP": 108,
    "MP": 0,
    "AP": 168,
    "SP": 42,
    "speed": 36,
    "growth": 1.173,
    "high_growth": 1.236,
    "title_level": 8,
    "skills": [],
    "gold": 0,
    "wood": 40,
    "soil": 60,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x0F63A9D5"],
    "stand": ["shape.wdf", "0x780A7A13"],
    "walk": ["shape.wdf", "0xAEEFFEB2"],
    "hit": ["shape.wdf", "0x31119883"],
    "beaten": ["shape.wdf", "0x16F3413F"],  
    "defence": ["shape.wdf", "0xC5CF4D09"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xE10AB87A"]
  },
  "shenbing": {
    "name": "神兵",
    "HP": 90,
    "MP": 0,
    "AP": 132,
    "SP": 72,
    "speed": 60,
    "growth": 1.203,
    "high_growth": 1.254,
    "title_level": 8,
    "skills": [],
    "gold": 65,
    "wood": 0,
    "soil": 35,
    "water": 0,
    "fire": 0,
    "run": ["shape.wdf", "0x1A1F8B29"],
    "stand": ["shape.wdf", "0x63D41486"],
    "walk": ["shape.wdf", "0x98071CDB"],
    "hit": ["shape.wdf", "0xC5676415"],
    "beaten": ["shape.wdf", "0x768E814C"],
    "defence": ["shape.wdf", "0xB9448E01"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0x2CC4FE10"]
  },
  "sheshengnvwa": {
    "name": "舍生女娲",
    "HP": 120,
    "MP": 168,
    "AP": 72,
    "SP": -29,
    "speed": -24,
    "growth": 1.224,
    "high_growth": 1.267,
    "title_level": 9,
    "skills": [[10, "longjuanyuji"],[30, "longtengshuijian"],[50, "longxiaojiutian"],[70, "jiaolongchuhai"]],
    "gold": 5,
    "wood": 0,
    "soil": 0,
    "water": 95,
    "fire": 0,
    "run": ["shape.wdf", "0x3F8D0A9B"],
    "stand": ["shape.wdf", "0xA90239E9"],
    "walk": ["shape.wdf", "0x4811E93F"],
    "hit": ["shape.wdf", "0x4D11532C"],
    "beaten": ["shape.wdf", "0x9FC8D7D7"],
    "defence": ["shape.wdf", "0x0D518B42"],
    "magic": ["shape.wdf", "0xE44571AA"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xB7FED2DC"]
  },
  "shenling": {
    "name": "神灵",
    "HP": 60,
    "MP": 168,
    "AP": 42,
    "SP": 76,
    "speed": 60,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 9,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 50,
    "fire": 50,
    "run": ["shape.wdf", "0x329FE1E9"],
    "stand": ["shape.wdf", "0x849CFCEB"],
    "walk": ["shape.wdf", "0x788F12EB"],
    "hit": ["shape.wdf", "0x9383411F"],
    "beaten": ["shape.wdf", "0x129ACE33"],
    "defence": ["shape.wdf", "0xB478D85B"],
    "magic": ["shape.wdf", "0x71146663"],
    "beaten_down": ["", "0x"],
    "static": ["shape.wdf", "0xF879501E"]
  },
  "taoshujing": {
    "name": "桃树精",
    "HP": 144,
    "MP": 0,
    "AP": 12,
    "SP": -306,
    "speed": -240,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 11,
    "skills": [],
    "gold": 0,
    "wood": 100,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "taohuaxian": {
    "name": "桃花仙",
    "HP": 72,
    "MP": 72,
    "AP": 48,
    "SP": 61,
    "speed": 48,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 11,
    "skills": [],
    "gold": 0,
    "wood": 100,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jingangxian": {
    "name": "金刚仙",
    "HP": 48,
    "MP": 216,
    "AP": 48,
    "SP": 45,
    "speed": 35,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 11,
    "skills": [],
    "gold": 100,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shitushou": {
    "name": "食土兽",
    "HP": 72,
    "MP": 72,
    "AP": 72,
    "SP": 61,
    "speed": 48,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 11,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 100,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "huangjinshou": {
    "name": "黄金兽",
    "HP": 12,
    "MP": 0,
    "AP": 180,
    "SP": 306,
    "speed": 240,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 12,
    "skills": [],
    "gold": 100,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shuilingxian": {
    "name": "水灵仙",
    "HP": 12,
    "MP": 360,
    "AP": 12,
    "SP": 45,
    "speed": 36,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 12,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 100,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "nishiguai": {
    "name": "泥石怪",
    "HP": 60,
    "MP": 0,
    "AP": 360,
    "SP": -612,
    "speed": -480,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 12,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 100,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "penhuoniu": {
    "name": "喷火牛",
    "HP": 96,
    "MP": 48,
    "AP": 96,
    "SP": 76,
    "speed": 60,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 12,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 100,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "qilinshou": {
    "name": "麒麟兽",
    "HP": 144,
    "MP": 144,
    "AP": 12,
    "SP": -306,
    "speed": -240,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 13,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 100,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "bingxuemo": {
    "name": "冰雪魔",
    "HP": 132,
    "MP": 0,
    "AP": 12,
    "SP": 306,
    "speed": 240,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 13,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 100,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "chiyanyao": {
    "name": "赤焰妖",
    "HP": 12,
    "MP": 72,
    "AP": 120,
    "SP": 91,
    "speed": 72,
    "growth": 1.275,
    "high_growth": 1.304,
    "title_level": 14,
    "skills": [],
    "gold": 20,
    "wood": 20,
    "soil": 20,
    "water": 20,
    "fire": 20,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shixie": {
    "name": "狮蝎",
    "HP": 45,
    "MP": 156,
    "AP": 120,
    "SP": 15,
    "speed": 12,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 14,
    "skills": [],
    "gold": 25,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 75,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "luoshaguiji": {
    "name": "罗刹鬼姬",
    "HP": 62,
    "MP": 360,
    "AP": 12,
    "SP": 0,
    "speed": 0,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 14,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 30,
    "water": 70,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "leishou": {
    "name": "雷兽",
    "HP": 102,
    "MP": 199,
    "AP": 12,
    "SP": -153,
    "speed": -120,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 14,
    "skills": [],
    "gold": 40,
    "wood": 0,
    "soil": 0,
    "water": 60,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jianjingling": {
    "name": "剑精灵",
    "HP": 60,
    "MP": 120,
    "AP": 12,
    "SP": 153,
    "speed": 120,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 14,
    "skills": [],
    "gold": 75,
    "wood": 0,
    "soil": 0,
    "water": 25,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "geliahao": {
    "name": "哥俩好",
    "HP": 120,
    "MP": 0,
    "AP": 180,
    "SP": 61,
    "speed": 48,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 14,
    "skills": [],
    "gold": 0,
    "wood": 70,
    "soil": 30,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jinlingshu": {
    "name": "金灵鼠",
    "HP": 90,
    "MP": 0,
    "AP": 165,
    "SP": 46,
    "speed": 39,
    "growth": 1.173,
    "high_growth": 1.173,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "minglingfeizi": {
    "name": "冥灵妃子",
    "HP": 138,
    "MP": 144,
    "AP": 12,
    "SP": 92,
    "speed": 72,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 14,
    "skills": [],
    "gold": 75,
    "wood": 0,
    "soil": 0,
    "water": 25,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "songshu": {
    "name": "松鼠",
    "HP": 72,
    "MP": 0,
    "AP": 168,
    "SP": 275,
    "speed": 216,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jialouluowang": {
    "name": "迦楼罗王",
    "HP": 12,
    "MP": 0,
    "AP": 288,
    "SP": 57,
    "speed": 45,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 14,
    "skills": [],
    "gold": 40,
    "wood": 0,
    "soil": 0,
    "water": 60,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jingwei": {
    "name": "精卫",
    "HP": 18,
    "MP": 120,
    "AP": 12,
    "SP": 191,
    "speed": 150,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 14,
    "skills": [],
    "gold": 25,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 75,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "yaohuolang": {
    "name": "妖火狼",
    "HP": 128,
    "MP": 0,
    "AP": 128,
    "SP": 267,
    "speed": 210,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 40,
    "water": 0,
    "fire": 60,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "minglei": {
    "name": "冥雷",
    "HP": 96,
    "MP": 36,
    "AP": 0,
    "SP": 316,
    "speed": 248,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 60,
    "soil": 0,
    "water": 40,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shenying": {
    "name": "蜃影",
    "HP": 90,
    "MP": 0,
    "AP": 335,
    "SP": -382,
    "speed": -300,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 0,
    "skills": [],
    "gold": 50,
    "wood": 0,
    "soil": 50,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jingxidagui": {
    "name": "精细大鬼",
    "HP": 20,
    "MP": 300,
    "AP": 180,
    "SP": -459,
    "speed": -360,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 0,
    "skills": [],
    "gold": 50,
    "wood": 0,
    "soil": 25,
    "water": 0,
    "fire": 25,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "linglixiaochong": {
    "name": "伶俐小虫",
    "HP": 150,
    "MP": 240,
    "AP": 0,
    "SP": 114,
    "speed": 90,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 25,
    "water": 75,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "xiaoxiong": {
    "name": "小熊",
    "HP": 96,
    "MP": 0,
    "AP": 122,
    "SP": 23,
    "speed": 20,
    "growth": 1.15,
    "high_growth": 1.15,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jiujie": {
    "name": "九戒",
    "HP": 160,
    "MP": 0,
    "AP": 880,
    "SP": -600,
    "speed": -737,
    "growth": 0.814,
    "high_growth": 0.814,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jixiangguo": {
    "name": "吉祥果",
    "HP": 80,
    "MP": 0,
    "AP": 0,
    "SP": 390,
    "speed": 480,
    "growth": 0.814,
    "high_growth": 0.814,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "tianlongnv": {
    "name": "天龙女",
    "HP": 660,
    "MP": 320,
    "AP": 0,
    "SP": -600,
    "speed": -737,
    "growth": 0.814,
    "high_growth": 0.814,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shenshouyanruyu": {
    "name": "神兽颜如玉",
    "HP": 10,
    "MP": 1200,
    "AP": 10,
    "SP": 600,
    "speed": 367,
    "growth": 0.612,
    "high_growth": 0.612,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shenshouwuye": {
    "name": "神兽五叶",
    "HP": 600,
    "MP": 0,
    "AP": 10,
    "SP": 440,
    "speed": 720,
    "growth": 0.612,
    "high_growth": 0.612,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shenshouchuiyunsou": {
    "name": "神兽垂云叟",
    "HP": 800,
    "MP": 1200,
    "AP": 10,
    "SP": 0,
    "speed": 0,
    "growth": 0.612,
    "high_growth": 0.612,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shenshoulangtaosha": {
    "name": "神兽浪淘沙",
    "HP": 600,
    "MP": 0,
    "AP": 1200,
    "SP": 0,
    "speed": 0,
    "growth": 0.612,
    "high_growth": 0.612,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shenshoufanshizhihun": {
    "name": "神兽范式之魂",
    "HP": 20,
    "MP": 0,
    "AP": 1100,
    "SP": 367,
    "speed": 600,
    "growth": 0.612,
    "high_growth": 0.612,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "qiannianlinghu": {
    "name": "千年灵狐",
    "HP": 130,
    "MP": 0,
    "AP": 200,
    "SP": 0,
    "speed": 0,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "longmenshuijiang": {
    "name": "龙门水将",
    "HP": 10,
    "MP": 0,
    "AP": 300,
    "SP": 80,
    "speed": 59,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "hushandashen": {
    "name": "护山大神",
    "HP": 130,
    "MP": 0,
    "AP": 200,
    "SP": 0,
    "speed": 0,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "nvzeizhiling": {
    "name": "女贼之灵",
    "HP": 90,
    "MP": 50,
    "AP": 20,
    "SP": 120,
    "speed": 88,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "yutu": {
    "name": "玉兔",
    "HP": 220,
    "MP": 0,
    "AP": 10,
    "SP": -200,
    "speed": 148,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "xunhaiyecha": {
    "name": "巡海夜叉",
    "HP": 10,
    "MP": 0,
    "AP": 350,
    "SP": 50,
    "speed": 37,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shouhuxiejiangjun": {
    "name": "守护蟹将军",
    "HP": 200,
    "MP": 60,
    "AP": 0,
    "SP": -270,
    "speed": 200,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "huangjinlishi": {
    "name": "黄巾力士",
    "HP": 90,
    "MP": 50,
    "AP": 20,
    "SP": 162,
    "speed": 120,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jinshenluohan": {
    "name": "金身罗汉",
    "HP": 60,
    "MP": 280,
    "AP": 40,
    "SP": 50,
    "speed": 37,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "baihuazhiling": {
    "name": "百花之灵",
    "HP": 10,
    "MP": 60,
    "AP": 10,
    "SP": 135,
    "speed": 100,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "yujianchou": {
    "name": "渔见愁",
    "HP": 70,
    "MP": 70,
    "AP": 70,
    "SP": 70,
    "speed": 51,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "pilishou": {
    "name": "霹雳手",
    "HP": 130,
    "MP": 0,
    "AP": 230,
    "SP": -100,
    "speed": 74,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "hubugui": {
    "name": "狐不皈",
    "HP": 180,
    "MP": 100,
    "AP": 0,
    "SP": -200,
    "speed": 148,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "bishuijinjingshou": {
    "name": "避水金睛兽",
    "HP": 130,
    "MP": 0,
    "AP": 200,
    "SP": 0,
    "speed": 0,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "huoqilin": {
    "name": "火麒麟",
    "HP": 200,
    "MP": 60,
    "AP": 10,
    "SP": -270,
    "speed": 200,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "taohuaniangzi": {
    "name": "桃花娘子",
    "HP": 60,
    "MP": 280,
    "AP": 40,
    "SP": 50,
    "speed": 37,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jingpanshizhe": {
    "name": "净盘使者",
    "HP": 10,
    "MP": 0,
    "AP": 350,
    "SP": 50,
    "speed": 37,
    "growth": 1.35,
    "high_growth": 1.35,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shenshouniumowang": {
    "name": "神兽牛魔王",
    "HP": 110,
    "MP": 0,
    "AP": 150,
    "SP": 26,
    "speed": 20,
    "growth": 1.3,
    "high_growth": 1.3,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  
  "chaojifeiyu": {
    "name": "超级飞鱼",
    "HP": 40,
    "MP": 200,
    "AP": 50,
    "SP": 78,
    "speed": 60,
    "growth": 1.3,
    "high_growth": 1.3,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "chaojizhizhu": {
    "name": "超级蜘蛛",
    "HP": 90,
    "MP": 150,
    "AP": 80,
    "SP": 13,
    "speed": 10,
    "growth": 1.3,
    "high_growth": 1.3,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "chaojihaigui": {
    "name": "超级海龟",
    "HP": 200,
    "MP": 100,
    "AP": 10,
    "SP": 0,
    "speed": 0,
    "growth": 1.3,
    "high_growth": 1.3,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "chaojichanchu": {
    "name": "超级蟾蜍",
    "HP": 110,
    "MP": 0,
    "AP": 150,
    "SP": 26,
    "speed": 20,
    "growth": 1.3,
    "high_growth": 1.3,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shenshounian": {
    "name": "神兽年",
    "HP": 10,
    "MP": 0,
    "AP": 10,
    "SP": 1100,
    "speed": 1797,
    "growth": 0.612,
    "high_growth": 0.612,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shenshouhuazhongxian": {
    "name": "神兽画中仙",
    "HP": 300,
    "MP": 0,
    "AP": 0,
    "SP": 900,
    "speed": 1470,
    "growth": 0.612,
    "high_growth": 0.612,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "longma　": {
    "name": "龙马　",
    "HP": 180,
    "MP": 0,
    "AP": 366,
    "SP": 0,
    "speed": 0,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "xiaolangtaosha": {
    "name": "小浪淘沙",
    "HP": 80,
    "MP": 0,
    "AP": 135,
    "SP": 0,
    "speed": 0,
    "growth": 1.15,
    "high_growth": 1.15,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "huapiniangzi": {
    "name": "画皮娘子",
    "HP": 24,
    "MP": 0,
    "AP": 384,
    "SP": 245,
    "speed": 192,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 0,
    "skills": [],
    "gold": 50,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 50,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "zhizunbao": {
    "name": "至尊包",
    "HP": 13,
    "MP": 14,
    "AP": 200,
    "SP": -100,
    "speed": -115,
    "growth": 1.15,
    "high_growth": 1.15,
    "title_level": 0,
    "skills": [],
    "gold": 50,
    "wood": 0,
    "soil": 0,
    "water": 50,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shenshoubaize": {
    "name": "神兽白泽",
    "HP": 1200,
    "MP": 0,
    "AP": 0,
    "SP": -490,
    "speed": -800,
    "growth": 0.612,
    "high_growth": 0.612,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jiayinxiaoshi": {
    "name": "佳音小使",
    "HP": 160,
    "MP": 110,
    "AP": 12,
    "SP": 127,
    "speed": 100,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jinbuhuan": {
    "name": "金不换",
    "HP": 80,
    "MP": 720,
    "AP": 0,
    "SP": 300,
    "speed": 369,
    "growth": 0.814,
    "high_growth": 0.814,
    "title_level": 0,
    "skills": [],
    "gold": 80,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 20,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "yaoxie": {
    "name": "妖蝎",
    "HP": 60,
    "MP": 0,
    "AP": 240,
    "SP": 229,
    "speed": 180,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 25,
    "soil": 75,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "bishuijingpo": {
    "name": "碧水精魄",
    "HP": 96,
    "MP": 32,
    "AP": 0,
    "SP": 306,
    "speed": 240,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 100,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "jixiemujiaren": {
    "name": "机械木甲人",
    "HP": 210,
    "MP": 210,
    "AP": 0,
    "SP": 30,
    "speed": 24,
    "growth": 1.275,
    "high_growth": 1.275,
    "title_level": 0,
    "skills": [],
    "gold": 50,
    "wood": 50,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "static": ["", "0x"]
  },
  "shihushou": {
    "name": "狮虎兽",
    "HP": 72,
    "MP": 0,
    "AP": 660,
    "SP": 264,
    "speed": 215,
    "growth": 0.814,
    "high_growth": 0.814,
    "title_level": 0,
    "skills": [],
    "gold": 0,
    "wood": 0,
    "soil": 0,
    "water": 0,
    "fire": 0,
    "run": ["", "0x"],
    "stand": ["", "0x"],
    "walk": ["", "0x"],
    "hit": ["", "0x"],
    "beaten": ["", "0x"],
    "defence": ["", "0x"],
    "magic": ["", "0x"],
    "beaten_down": ["", "0x"],
    "dead": ["", "0x"]
  }
}