mythical = {
    "zixiaxianzi": {
        "name": "紫霞仙子",
        "HP": 40,
        "MP": 200,
        "AP": 50,
        "SP": 65,
        "Speed": 50,
        "growth": 1.300,
        "high_growth": 1.300,
        "title_level": 0,
        "skills": [[10, "diyuliehuo"], [30, "tianleinuhuo"], [50, "sanweizhenhuo"], [70, "liehuojiaoyang"]],
        "gold": 0,
        "wood": 0,
        "soil": 0,
        "water": 0,
        "fire": 0,
        "run": ["shape.wdf", "0xF1AA55F6"],
        "stand": ["shape.wdf", "0xAC257CE0"],
        "walk": ["shape.wdf", "0x85BD39BA"],
        "hit": ["shape.wdf", "0xDD102EC4"],
        "beaten": ["shape.wdf", "0x27F8E12A"],
        "defence": ["shape.wdf", "0xE436F2B8"],
        "magic": ["shape.wdf", "0x07FF0EF2"],
        "beaten_down": ["", "0x"],
        "dead": ["", ""],
        "static": ["shape.wdf", "0xA2C8444D"]
    },
    "jinghelongwang": {
        "name": "泾河龙王",
        "HP": 10,
        "MP": 70,
        "AP": 10,
        "SP": 156,
        "Speed": 120,
        "growth": 1.300,
        "high_growth": 1.300,
        "title_level": 0,
        "skills": [[10, "longjuanyuji"], [30, "longtengshuijian"], [50, "longxiaojiutian"], [70, "jiaolongchuhai"]],
        "run": ["shape.wdf", "0x8EE6F927"],
        "stand": ["shape.wdf", "0xE78B25C1"],
        "walk": ["shape.wdf", "0x12D27416"],
        "hit": ["shape.wdf", "0x097183AC"],
        "beaten": ["shape.wdf", "0x3E11F5D1"],
        "defence": ["shape.wdf", "0x3C35328F"],
        "magic": ["", "0x"],
        "magic_1": ["shape.wdf", "0xA62F51EA"],
        "beaten_down": ["", "0x"],
        "dead": ["", ""],
        "static": ["shape.wdf", "0xBEAED63A"]
    },
    "longtaizi": {
        "name": "龙太子",
        "HP": 55,
        "MP": 200,
        "AP": 50,
        "SP": 65,
        "Speed": 50,
        "growth": 1.300,
        "high_growth": 1.300,
        "title_level": 0,
        "skills": [[10, "longjuanyuji"], [30, "longtengshuijian"], [50, "longxiaojiutian"], [70, "jiaolongchuhai"]],
        "gold": 0,
        "wood": 0,
        "soil": 0,
        "water": 0,
        "fire": 0,
        "run": ["shape.wdf", "0x0DD50F58"],
        "stand": ["shape.wdf", "0x4FED68E0"],
        "walk": ["shape.wdf", "0xCE7F6140"],
        "hit": ["shape.wdf", "0x4335C346"],
        "beaten": ["shape.wdf", "0xCAB2E6BF"],
        "defence": ["shape.wdf", "0xE6AD8241"],
        "magic": ["shape.wdf", "0xD12EB5E3"],
        "beaten_down": ["", "0x"],
        "dead": ["", ""],
        "unknown": ["shape.wdf", "0xCC61903E"],
        "static": ["shape.wdf", "0xB5A9217F"]
    },
    "zhizunxiaobao": {
        "name": "至尊小宝",
        "HP": 55,
        "MP": 200,
        "AP": 50,
        "SP": 65,
        "speed": 50,
        "growth": 1.3,
        "high_growth": 1.3,
        "title_level": 0,
        "skills": [[10, "feishazoushi"], [30, "chengfengpolang"], [50, "taiyishengfeng"], [70, "fengleiyongdong"]],
        "gold": 0,
        "wood": 0,
        "soil": 0,
        "water": 0,
        "fire": 0,
        "run": ["shape.wdf", "0xEFC69175"],
        "stand_normal": ["shape.wdf", "0xE3587E7B"],
        "stand_normal_white": ["shape.wdf", "0xEA27AD31"],
        "stand": ["shape.wdf", "0xE985EE5D"],
        "walk": ["shape.wdf", "0xE2DD30D1"],
        "hit": ["shape.wdf", "0x3E0F197F"],
        "beaten": ["shape.wdf", "0x15BC238B"],
        "defence": ["shape.wdf", "0x8C14660A"],
        "magic": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
        "static": ["", "0x"],
        "walk_dramatic": ["shape.wdf", "0xFB629346"]
    },
    "bitaoniangzi": {
        "name": "碧桃娘子",
        "HP": 90,
        "MP": 150,
        "AP": 80,
        "SP": 13,
        "speed": 10,
        "growth": 1.3,
        "high_growth": 1.3,
        "title_level": 0,
        "skills": [],
        "gold": 0,
        "wood": 0,
        "soil": 0,
        "water": 0,
        "fire": 0,
        "run": ["shape.wdf", "0xF33532BD"],
        "stand": ["shape.wdf", "0x1881A745"],
        "walk": ["shape.wdf", "0x61A8F3FF"],
        "hit": ["shape.wdf", "0xFF037975"],
        "beaten": ["shape.wdf", "0x89787A04"],
        "defence": ["shape.wdf", "0xF4DAD89F"],
        "magic": ["shape.wdf", "0x9069AE02"],  # 1
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
        "static": ["shape.wdf", "0x2E305A78"]
    },
    "chaojidushe": {
        "name": "超级毒蛇",
        "HP": 55,
        "MP": 200,
        "AP": 50,
        "SP": 65,
        "speed": 50,
        "growth": 1.3,
        "high_growth": 1.3,
        "title_level": 0,
        "skills": [],
        "gold": 0,
        "wood": 0,
        "soil": 0,
        "water": 0,
        "fire": 0,
        "run": ["", "0x"],
        "stand": ["", "0x"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
        "static": ["", "0x"]
    },
    "qingxiaxianzi": {
        "name": "青霞仙子",
        "HP": 200,
        "MP": 100,
        "AP": 10,
        "SP": 0,
        "speed": 0,
        "growth": 1.3,
        "high_growth": 1.3,
        "title_level": 0,
        "skills": [],
        "gold": 0,
        "wood": 0,
        "soil": 0,
        "water": 0,
        "fire": 0,
        "run": ["shape.wdf", "0x78453897"],
        "stand": ["shape.wdf", "0x4087B323"],
        "walk": ["shape.wdf", "0x58B7A942"],
        "hit": ["shape.wdf", "0x9CCED9F3"],
        "beaten": ["shape.wdf", "0x420A8983"],
        "defence": ["shape.wdf", "0x3E4A6073"],
        "magic": ["shape.wdf", "0xF7545337"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
        "static": ["shape.wdf", "0x265B5E90"]
    },
    "jingjing": {
        "name": "晶晶",
        "HP": 70,
        "MP": 0,
        "AP": 160,
        "SP": 91,
        "speed": 70,
        "growth": 1.3,
        "high_growth": 1.3,
        "title_level": 0,
        "skills": [],
        "gold": 0,
        "wood": 0,
        "soil": 0,
        "water": 0,
        "fire": 0,
        "run": ["shape.wdf", "0xDD9132B6"],
        "stand": ["shape.wdf", "0xF16C471C"],
        "walk": ["shape.wdf", "0x9957A256"],
        "hit": ["shape.wdf", "0x7963E3C2"],
        "beaten": ["shape.wdf", "0x7FE8694C"],
        "defence": ["shape.wdf", "0xEF4D4EBB"],
        "magic": ["shape.wdf", "0xE1D303C3"],  # 1
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
        "static": ["shape.wdf", "0xF5D47E2E"]
      },
}
