NPC = {
    "juexin": {
        "name": "觉新",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x015B95C2"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    }, 
    "jiutoujingguai": {
        "name": "九头精怪",
        "run": ["shape.wdf", "0x517C09D7"],
        "stand": ["shape.wdf", "0x0162E9DE"],
        "walk": ["shape.wdf", "0x0B8285F9"],
        "hit": ["shape.wdf", "0xC9EC64BB"],
        "beaten": ["shape.wdf", "0xCEF45818"],
        "defence": ["shape.wdf", "0x540D1100"],
        "magic": ["shape.wdf", "0xBB56EF5A"],
        "static": ["shape.wdf", "0x7CAF3ABB"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "shibin": {
        "name": "士兵",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x03A423A7"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "bangpaizongguan": {
        "name": "帮派总管",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x06F1DE7D"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "fengjitiepu": {
        "name": "冯铁匠",
        "run": ["", "0x"],
        "stand": [["shape.wdf", "0x0734C9CA"], ["shape.wdf", "0x7103B70E"]],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "zhubajie": {
        "name": "猪八戒",
        "run": ["shape.wdf", "0xEF49D689"],
        "stand": ["shape.wdf", "0xADE4CBF2"],
        "walk": ["shape.wdf", "0x85C12349"],
        "hit": ["shape.wdf", "0x1D7E5D02"],
        "beaten": ["shape.wdf", "0x94C75679"],
        "defence": ["shape.wdf", "0x00C8DD73"],
        "magic": ["shape.wdf", "0xAFF97BB0"],
        "static": ["shape.wdf", "0x046ADE41"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "niumowang": {
        "name": "牛魔王",
        "run": ["shape.wdf", "0x42B244C0"],
        "stand": ["shape.wdf", "0x0B69B44D"],
        "walk": ["shape.wdf", "0xFBB7A2A2"],
        "hit": ["shape.wdf", "0xDFAB4445"],
        "beaten": ["shape.wdf", "0x90BB1A9E"],
        "defence": ["shape.wdf", "0xC096C013"],
        "magic": ["shape.wdf", "0x65EB0501"],
        "static": ["shape.wdf", "0x5867F741"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "tianjiang": {
        "name": "天将",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x35F5C343"],
        "walk": ["shape.wdf", "0x028B91D6"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "tianjiang_jibing": {
        "name": "天将戟兵",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x1D8F9ABB"],
        "walk": ["shape.wdf", "0x04103E1D"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "panguan": {
        "name": "判官",
        "run": ["shape.wdf", "0xA37B5C8B"],
        "stand": ["shape.wdf", "0x16B69387"],
        "walk": ["shape.wdf", "0x32C68CC9"],
        "hit": ["shape.wdf", "0xD572D8E4"],
        "beaten": ["shape.wdf", "0xA8312FDB"],
        "defence": ["shape.wdf", "0x4E4C9223"],
        "magic": ["shape.wdf", "0x1A7C6CAC"],
        "static": ["shape.wdf", "0x3A11C300"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "panguan_pink": {
        "name": "判官",
        "run": ["shape.wdf", "0x60D75C2E"],
        "stand": ["shape.wdf", "0xBB873380"],
        "walk": ["shape.wdf", "0x1646EF75"],
        "hit": ["shape.wdf", "0x701D3CD2"],
        "beaten": ["shape.wdf", "0x0997D407"],
        "defence": ["shape.wdf", "0xB8963FF6"],
        "magic": ["shape.wdf", "0xC2B4BFF3"],  # 1
        "static": ["shape.wdf", "0x4C3059DE"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "panguan_red_pink": {
        "name": "判官",
        "run": ["shape.wdf", "0x2C2DA4EB"],
        "stand": ["shape.wdf", "0x5F16E6B6"],
        "walk": ["shape.wdf", "0xF87D8A2A"],
        "hit": ["shape.wdf", "0x2B307A3F"],
        "beaten": ["shape.wdf", "0xDE2A0E4A"],
        "defence": ["shape.wdf", "0x487DC0D6"],
        "magic": ["shape.wdf", "0x4E3EBD5F"],
        "static": ["shape.wdf", "0xF3F3CA4F"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "panguan_purple": {
        "name": "判官",
        "run": ["shape.wdf", "0x76748165"],
        "stand": ["shape.wdf", "0x22C46AE2"],
        "walk": ["shape.wdf", "0xBC948912"],
        "hit": ["shape.wdf", "0x8316CF85"],
        "beaten": ["shape.wdf", "0xDE5A0BC6"],
        "defence": ["shape.wdf", "0x0D6E35D8"],
        "magic": ["shape.wdf", "0x23F14940"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
        "static": ["shape.wdf", "0x17E56AA5"]
    },
    "panguan_grass_green": {
        "name": "判官",
        "run": ["shape.wdf", "0x425458D5"],  # 草绿
        "stand": ["shape.wdf", "0x5949EC31"],  # QIAN LAN  719
        "walk": ["shape.wdf", "0xDC2C33F6"],
        "hit": ["shape.wdf", "0x83D92AE3"], 
        "beaten": ["shape.wdf", "0x4A238044"],  # 草绿
        "defence": ["shape.wdf", "0x97AD4D51"],  # 972
        "magic": ["shape.wdf", "0xF49E974E"],  # 1
        "static": ["shape.wdf", "0x5FF3EEFD"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "panguan_green": {
        "name": "判官",
        "run": ["shape.wdf", "0x67603C74"],
        "stand": ["shape.wdf", "0x6EA5597F"],
        "walk": ["shape.wdf", "0x94E21235"],
        "hit": ["shape.wdf", "0x7AD386DF"],  # 548
        "beaten": ["shape.wdf", "0x55E342FC"],
        "defence": ["shape.wdf", "0x6CDDC04D"],
        "magic": ["shape.wdf", "0xB255F50B"],
        "static": ["shape.wdf", "0xB94403FE"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "panguan_green_blue": {
        "name": "判官",
        "run": ["shape.wdf", "0xB1F9F9ED"],
        "stand": ["shape.wdf", "0x0B9AC09C"],  # 
        "walk": ["shape.wdf", "0xEB15762A"],
        "hit": ["shape.wdf", "0x54E2C4FC"],
        "beaten": ["shape.wdf", "0x2803B38C"],
        "defence": ["shape.wdf", "0xCDEE504D"],
        "magic": ["shape.wdf", "0xBB81A407"],
        "static": ["shape.wdf", "0x7F354CC7"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "panguan_blue": {
        "name": "判官",
        "run": ["shape.wdf", "0x448D60E8"],
        "stand": ["shape.wdf", "0x68BC67E8"],
        "walk": ["shape.wdf", "0x4441ECB7"],
        "hit": ["shape.wdf", "0x116605E1"],
        "beaten": ["shape.wdf", "0x139C8FF3"], 
        "defence": ["shape.wdf", "0x4312B448"],
        "magic": ["shape.wdf", "0x26A9EF1F"],
        "static": ["shape.wdf", "0x2296B535"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "panguan_deep_blue": {
        "name": "判官",
        "run": ["shape.wdf", "0xFAA9511F"],
        "stand": ["shape.wdf", "0xA0DA9F03"],
        "walk": ["shape.wdf", "0x558B14D5"],
        "hit": ["shape.wdf", "0x15F50CFF"],
        "beaten": ["shape.wdf", "0x455697FE"],  # 454
        "defence": ["shape.wdf", "0x9402033C"],
        "magic": ["shape.wdf", "0x21B6E8AA"],
        "static": ["shape.wdf", "0xA5B436EE"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "panguan_red": {
        "name": "判官",
        "run": ["shape.wdf", "0xA47E429C"],
        "stand": ["shape.wdf", "0xEE9F2B14"],
        "walk": ["shape.wdf", "0x26992A08"],
        "hit": ["shape.wdf", "0x12272DD4"],
        "beaten": ["shape.wdf", "0x493D82C7"],
        "defence": ["shape.wdf", "0x27E5B04A"],
        "magic": ["shape.wdf", "0x6F392D1D"],
        "static": ["shape.wdf", "0x4805344E"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "panguan_yellow": {
        "name": "判官",
        "run": ["shape.wdf", "0x4AEA616C"],
        "stand": ["shape.wdf", "0xE8B26ECF"],
        "walk": ["shape.wdf", "0x7FB2D392"],
        "hit": ["shape.wdf", "0xF22082F6"],
        "beaten": ["shape.wdf", "0x71A3B8A4"],
        "defence": ["shape.wdf", "0x13D7CFF7"],
        "magic": ["shape.wdf", "0xCE391F52"],  # 1
        "static": ["shape.wdf", "0x9F726471"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "niutou": {
        "name": "牛头",
        "run": ["shape.wdf", "0xFA3CAFE4"],
        "stand": ["shape.wdf", "0xD817F82F"],
        "walk": ["shape.wdf", "0x7F2ABF21"],
        "hit": ["shape.wdf", "0x75D7E3ED"],
        "beaten": ["shape.wdf", "0xA85E8726"],  # 1068
        "defence": ["shape.wdf", "0x052D9E0F"],
        "magic": ["", "0x"],
        "static": ["shape.wdf", "0xE6E7DE44"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "tianyishenjiang": {
        "name": "天一神将",
        "run": ["shape.wdf", "0x345F9312"],
        "stand": ["shape.wdf", "0x6EFE5DD3"],
        "walk": ["shape.wdf", "0x05B6E64F"],
        "hit": ["shape.wdf", "0x34C5779E"],
        "beaten": ["shape.wdf", "0xE425B3FE"],
        "defence": ["shape.wdf", "0x03847C1E"],
        "magic": ["shape.wdf", "0xA49609C2"],  # 1
        "static": ["shape.wdf", "0x790BD1B7"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "shengdanlaoren": {
        "name": "圣诞老人",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xDE7DA687"],
        "walk": ["shape.wdf", "0x1210A82F"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "sunwukong": {
        "name": "孙悟空",
        "run": ["shape.wdf", "0x047501C6"],  # 
        "stand": ["shape.wdf", "0x56BC24B9"],
        "walk": ["shape.wdf", "0x92955417"],  # big  # 945
        "hit": ["shape.wdf", "0x243AFDBA"],  # big
        "beaten": ["shape.wdf", "0x3AE2A8F4"],
        "defence": ["shape.wdf", "0x1EF2922D"],  # big
        "magic": ["", "0x"],
        "static": ["", "0x"],  # 
        "beaten_down": ["", "0x"],
        "dead": ["shape.wdf", "0x809437CF"],
        "gas": ["shape.wdf", "0x49D3FA06"]
    },
    "sunwukong_small": {
        "name": "孙悟空",
        "run": ["shape.wdf", "0x1349DAA5"],  # small
        "stand": ["shape.wdf", "0x6831DDE1"],
        "walk": ["shape.wdf", "0x2C4D8EC8"],  # small
        "hit": ["shape.wdf", "0x6C1336EC"],  # 
        "beaten": ["shape.wdf", "0x5DE938BA"],
        "defence": ["shape.wdf", "0xB3A2B015"],  # 
        "magic": ["shape.wdf", "0xE8C2C0A4"],
        "static": ["shape.wdf", "0x14692807"],  # small
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
        "stand_9": ["shape.wdf", "0xF7A903E3"]  # 挠
    },
    "guanyin_sit": {
        "name": "观音",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x0405C585"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "mengpo": {
        "name": "孟婆",
        "run": ["shape.wdf", "0xFF851D2E"],
        "stand": ["shape.wdf", "0xAFA62A72"],  # D2EBBC01
        "stand2": [["shape.wdf", "0x150F87B9"], ["shape.wdf", "0x8F74E2E1"]],  # 敲地板，伸手
        "walk": ["shape.wdf", "0xCB62E343"],  # 1593
        "hit": ["shape.wdf", "0xED6DCE25"],
        "beaten": ["shape.wdf", "0x4EB6E12D"],
        "defence": ["", "0x"],
        "magic": ["shape.wdf", "0x5FA6F60E"],
        "static": ["", "0x"],
        "beaten_down": ["shape.wdf", "0x3A9B3ED0"],
        "dead": ["", "0x"],
    },
    "tianguan": {
        "name": "天官",
        "run": ["shape.wdf", "0xF9E47CD2"],
        "stand": ["shape.wdf", "0x96DB51AB"],
        "walk": ["shape.wdf", "0x58F4B663"],
        "hit": ["shape.wdf", "0x15125FC7"],
        "beaten": ["shape.wdf", "0x5868EDBE"],
        "defence": ["shape.wdf", "0x87EF3814"],
        "magic": ["", "0x"],
        "static": ["shape.wdf", "0xE1A120FF"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "zhenyuandaxian": {
        "name": "镇元大仙",
        "jag": ["shape.wdf", "0xA4EC9638"],
        "run": ["shape.wdf", "0x3732FF71"],
        "stand": ["shape.wdf", "0x22406E66"],
        "stand2": [["shape.wdf", "0x75CDF97C"], ["shape.wdf", "0xD73020CD"]],  # 1356
        "walk": ["shape.wdf", "0x5E8CC3F3"],
        "hit": ["shape.wdf", "0x9F64FB32"],
        "beaten": ["shape.wdf", "0x5AD58D24"],
        "defence": ["shape.wdf", "0xAE592351"],
        "magic": ["shape.wdf", "0x16385B4D"],
        "static": ["", "0x"],
        "beaten_down": ["shape.wdf", "0x054F4C87"],
        "dead": ["", "0x"],
    },
    "luohan_float": {
        "name": "罗汉",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x0B510184"],  # ["shape.wdf", "0x2D7EDC9B"]
        "stand2": ["shape.wdf", "0x7CBCFF37"],
        "walk": ["", "0x"],
        "hit": ["shape.wdf", "0x408DE185"],
        "beaten": ["shape.wdf", "0xBC1BD809"],
        "defence": ["shape.wdf", "0x113B69E8"],
        "magic": ["shape.wdf", "0xA9847201"],  # 2
        "static": ["shape.wdf", "0x59B3FCAD"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "caizhu": {
        "name": "财主",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x0BB9C549"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "taishanglaojun": {
        "name": "太上老君",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x3599D5C3"],
        "walk": ["shape.wdf", "0x16505471"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "yuefanglaoban": {
        "name": "乐坊老板",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x165AEB4C"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "hujingde": {
        "name": "胡敬德",
        "run": ["shape.wdf", "0x802136BA"],
        "stand": ["shape.wdf", "0x8FEDE4B5"],
        "walk": ["shape.wdf", "0x1708205C"],
        "hit": ["shape.wdf", "0x57EDEA8E"],
        "beaten": ["shape.wdf", "0x9E9C0CEA"],
        "defence": ["shape.wdf", "0x249719A0"],
        "magic": ["", "0x"],
        "static": ["shape.wdf", "0xA9B78CF6"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "mamian": {
        "name": "马面",
        "run": ["shape.wdf", "0xE26DD56F"],
        "stand": ["shape.wdf", "0xCB48E23B"],
        "walk": ["shape.wdf", "0x99AC3A10"],
        "hit": ["shape.wdf", "0x17A0338A"],
        "beaten": ["shape.wdf", "0xD55B8806"],
        "defence": ["shape.wdf", "0xFB352928"],
        "magic": ["", "0x"],
        "static": ["shape.wdf", "0xB350A5B4"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "baima": {
        "name": "白马",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x18505DEA"],
        "walk": ["shape.wdf", "0x51863950"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "laojia": {
        "name": "老贾",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x1AA01951"],
        "walk": ["shape.wdf", "0x5DFA3BB9"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },

    "qingloulaoban": {
        "name": "青楼老板",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x1BB1AF36"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiaohongzhizhu": {
        "name": "小红蜘蛛",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xE202FF07"],
        "walk": ["shape.wdf", "0x1C18F71D"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiaozhizhu": {
        "name": "小蜘蛛",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xCAFDA26D"],
        "walk": ["shape.wdf", "0x865B2F39"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiaoheizhizhu": {
        "name": "小黑蜘蛛",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x2B2F51B2"],
        "walk": ["shape.wdf", "0xC5A63D43"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "jiehunbaitang": {
        "name": "结婚拜堂",  # 347
        "stand_1": ["shape.wdf", "0x426F4075"],  # 三拜
        "stand_3": ["shape.wdf", "0x1C94A58B"],  # 作揖
    },
    "linghou": {
        "name": "灵猴",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x1D544C7E"],
        "walk": ["shape.wdf", "0xB014F3E5"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "shaseng": {
        "name": "沙僧",
        "run": ["shape.wdf", "0x5C2C1C4D"],
        "stand": ["shape.wdf", "0x6E7015D9"],
        "walk": ["shape.wdf", "0xF58104E2"],
        "hit": ["shape.wdf", "0x1D90BAA0"],
        "beaten": ["shape.wdf", "0xFAADCE7F"],
        "defence": ["shape.wdf", "0x63DF2FE0"],
        "magic": ["shape.wdf", "0xBB5DC671"],
        "static": ["shape.wdf", "0x9E8754B2"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "sandawang": {
        "name": "三大王",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x228D340F"],
        "walk": ["shape.wdf", "0x2059CBB0"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "putilaozu": {
        "name": "菩提老祖",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x2073F650"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "yuelao": {
        "name": "月老",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xA33DB160"],
        "walk": ["shape.wdf", "0x20A19816"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "fangmingfangzhang": {
        "name": "法明方丈",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x21EAE195"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "shengdanshu": {
        "name": "圣诞树",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x234BC75"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "wangmuniangniang": {
        "name": "王母娘娘",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x248A3E4C"],
        "walk": ["shape.wdf", "0x2B2CC199"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "lijing": {
        "name": "李靖",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x2596EC14"],
        "walk": ["shape.wdf", "0x431A24FA"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "nezha": {
        "name": "哪吒",
        "run": ["", "0x"],
        "stand_normal": ["shape.wdf", "0x5903D418"],
        "stand": ["shape.wdf", "0x259EC5A7"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "qiaofu": {
        "name": "樵夫",
        "run": ["shape.wdf", "0xA266472E"], 
        "jag": ["shape.wdf", "0x25C2E634"],
        "stand": ["shape.wdf", "0x2CCF7B23"],
        "stand_normal": [["shape.wdf", "0xBC6BD1E8"], ["shape.wdf", "0xCAB5EFEB"]],
        "walk": ["shape.wdf", "0x8736E40D"],
        "hit": ["shape.wdf", "0xB1043F77"],
        "beaten": ["shape.wdf", "0x9852873F"],
        "defence": ["shape.wdf", "0x3804781A"],
        "magic": ["shape.wdf", "0x0E4A5F8B"],
        "static": ["", "0x"],
        "beaten_down": ["shape.wdf", "0xAB6D17B1"],
        "dead": ["", "0x"],
    },
    "laoshu": {
        "name": "老鼠",
        "run": ["", "0x"],
        "stand": ["", "0x"],
        "walk": ["shape.wdf", "0xEA36DB67"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["shape.wdf", "0x2634AAFE"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "chenfuren": {
        "name": "陈夫人",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x2C2259AB"],
        "walk": ["shape.wdf", "0xB0250DEE"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "fuzhuangdianlaoban": {
        "name": "服装店老板",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x2EB42770"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "cuihua": {
        "name": "翠花",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x70357245"],
        "walk": ["shape.wdf", "0x3790FE0A"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "chuanfu": {
        "name": "船夫",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x767095C2"],
        "walk": ["shape.wdf", "0x3792B5F3"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "chaojiwuyi": {
        "name": "超级巫医",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x3A16E96D"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "heima": {
        "name": "黑马",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x672A13B6"],
        "walk": ["shape.wdf", "0x3BBFEBDE"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "yuhuangdadi": {
        "name": "玉皇大帝",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xEB00DE5F"],
        "walk": ["shape.wdf", "0x3C7DB1FD"],  # 1473
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "shamochuanfu": {
        "name": "沙漠船夫",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x4ED41E93"],
        "walk": ["shape.wdf", "0x3DD602B8"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "ji": {
        "name": "鸡",  # 1427
        "run": ["shape.wdf", "0xE21F96D1"],
        "jag": ["shape.wdf", "0x3FC3319A"],
        "stand": ["shape.wdf", "0x3E2E8B83"],
        "stand_shanchibang": ["shape.wdf", "0xCD9D7671"],
        "eat": ["shape.wdf", "0xF63FDBF2"],
        "walk": ["shape.wdf", "0x6EC8DF52"],
        "hit": ["shape.wdf", "0x9EF0F27B"],
        "beaten": ["shape.wdf", "0x7CFD46DC"], # ["shape.wdf", "0x4A68F4C0"],
        "defence": ["", "0x"],
        "magic": ["shape.wdf", "0x7ED0FDAC"],
        "static": ["", "0x"],
        "beaten_down": ["shape.wdf", "0x989C3F24"],
        "dead": ["", "0x"],
    },
    "erdawang": {
        "name": "二大王",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x50355C48"],
        "walk": ["shape.wdf", "0x403A153E"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "erpinshiwei": {
        "name": "二品侍卫",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x40B1BCC3"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "sunpopo": {
        "name": "孙婆婆",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x7555A8D0"],
        "walk": ["shape.wdf", "0x4468668F"],  # 627
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiaobianfu": {
        "name": "小蝙蝠",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x46656918"],
        "walk": ["shape.wdf", "0x8BC5D68F"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "chengyaojin": {
        "name": "程咬金",
        "run": ["shape.wdf", "0xB9DD2487"],
        "stand": ["shape.wdf", "0x48B4D93D"],
        "walk": ["shape.wdf", "0xA0334BC5"],
        "hit": ["shape.wdf", "0x78D10E0B"],
        "beaten": ["shape.wdf", "0xD86A15E2"],
        "defence": ["shape.wdf", "0x6AC6D271"],
        "magic": ["", "0x"],
        "static": ["shape.wdf", "0xAFFC26EB"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiaoheibianfu": {
        "name": "小黑蝙蝠",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x49734EA8"],
        "walk": ["shape.wdf", "0xFF7FBE19"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "nongfu": {  # 锄头
        "name": "农夫",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x5D14A411"],
        "walk": ["shape.wdf", "0x4E0B8DAC"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "touzi_2": {
        "name": "骰子",
        "random": ["shape.wdf", "0x54D687BC"],
    },
    "touzi_1": {
        "name": "",
        "123456": ["shape.wdf", "0x5641D9BE"],
    },
    "zhenghunren": {
        "name": "证婚人",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x56738B45"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "taibaijinxing": {
        "name": "太白金星",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xCA3334FF"],
        "walk": ["shape.wdf", "0x5745E837"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiaolvzhizhu": {
        "name": "小绿蜘蛛",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xBD6E9351"],  # 1289
        "walk": ["shape.wdf", "0x5ACD2AB2"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiaopangxie": {
        "name": "小螃蟹",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x5E518501"],
        "walk": ["shape.wdf", "0xA730B0F2"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "laofuren": {
        "name": "老夫人",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x81F4F89D"],
        "walk": ["shape.wdf", "0x600BA182"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiaolvshe": {
        "name": "小绿蛇",
        "run": ["shape.wdf", "0x6246AA1B"],
        "stand": ["shape.wdf", "0x13FF267B"],  # 小绿蛇  stand 1182
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "laoban_suanpan": {  # 算盘
        "name": "老板",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x64E5C547"],
        "walk": ["", "0x"],  # 731
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "baiwuchang": {
        "name": "白无常",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x67B85348"],
        "walk": ["shape.wdf", "0x837D7776"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "tiejiang_aolai": {  # 红色衣服，半裸
        "name": "铁匠",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x67C56BF0"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "qinqiong": {
        "name": "秦琼",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x6843A912"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "kaoguan": {
        "name": "考官",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x6ABF75AD"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "tudi": {
        "name": "土地",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x81895D83"],
        "walk": ["shape.wdf", "0x6E805BF9"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "laoban_shanzi": {
        "name": "老板",
        "run": ["", "0x"],
        "stand": ["", "0x"],
        "walk": ["shape.wdf", "0x703420B3"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiaohuangshe": {
        "name": "小黄蛇",
        "run": ["shape.wdf", "0x202892E0"],
        "stand": ["shape.wdf", "0x70CBC140"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "wuqidianlaoban": {
        "name": "武器店老板",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x732407B7"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiaobaiyu": {
        "name": "小白鱼",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x74CAC069"],
        "walk": ["shape.wdf", "0x743721EC"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "tiejiang_luoyang": {  # 半裸， 黑色裤子
        "name": "铁匠",
        "run": ["", "0x"],
        "stand": [["shape.wdf", "0x75BB33D2"]],  # 摆锤
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "zongma": {
        "name": "棕马",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x76DA1B74"],
        "walk": ["shape.wdf", "0xC378B04A"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "longwang": {
        "name": "龙王",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x810E3469"],
        "walk": ["shape.wdf", "0x77748072"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiannv": {
        "name": "仙女",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x7792B6DA"],
        "walk": ["shape.wdf", "0xDB11C815"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "daniu": {
        "name": "大牛",  # 男童
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xDCF6A150"],
        "walk": ["shape.wdf", "0x7C3B4FB7"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "fangzhang": {
        "name": "方丈",
        "run": ["", "0x"],
        "stand_heshi": ["shape.wdf", "0x87573929"],
        "stand": ["shape.wdf", "0xB73531B1"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "jiudianlaoban": {
        "name": "酒店老板",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x8783CF82"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "mubei": {
        "name": "墓碑",
        "static": ["shape.wdf", "0x87C1D9CC"],
    },
    "shusheng": {
        "name": "书生",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xAE82050D"],
        "walk": ["shape.wdf", "0x8DB0C74C"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiaoer": {
        "name": "小二",
        "stand2": ["shape.wdf", "0xC756DE61"],
        "stand": ["shape.wdf", "0x8F5E39E1"],
    },
    "xiannv_pink": {
        "name": "仙女",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x93A1B0A9"],
        "walk": ["shape.wdf", "0xEC91EDA2"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "nantong": {
        "name": "男童",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x9493C216"],
        "squat": ["shape.wdf", "0xE759FD0F"],
    },
    "xiaobaishe": {
        "name": "小白蛇",
        "run": ["shape.wdf", "0xDDF4FEC5"],
        "stand": ["shape.wdf", "0x9749A996"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "qigai": {
        "name": "乞丐",  # 1586
        "beg": ["shape.wdf", "0xFF1F0166"],
        "stand": ["shape.wdf", "0xBF882D3F"],
        "walk": ["shape.wdf", "0x97CDC297"]
    },
    "zongse_bird": {
        "name": "棕色小鸟",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x9EBF10CA"],
        "fly": ["shape.wdf", "0xD6F382BA"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "huangshulang": {
        "name": "黄鼠狼",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xA56A27E1"],
        "walk": ["shape.wdf", "0xD1E67B5B"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "shenzongseniu": {
        "name": "深棕色牛",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0x87851F1F"],
        "walk": ["shape.wdf", "0x206EF2EB"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "qianzhuanglaoban": {
        "name": "钱庄老板",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xA9F796EA"],  # 白帽子
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "dadawang": {
        "name": "大大王",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xCE62A786"],
        "walk": ["shape.wdf", "0xAD23D962"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "laotou_hese": {
        "name": "老头",  # 褐色
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xAD7A1BD3"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "helaocai": {
        "name": "何老才",
        "sit": ["shape.wdf", "0xFD419E2C"],
        "stand": ["shape.wdf", "0xAEDFE85F"]
    },
    "nv_yellow_purple": {
        "name": "读书女",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xAF20E948"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "heiwuchang": {
        "name": "黑无常",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xB181318C"],
        "walk": ["shape.wdf", "0xF250443E"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "lishimin": {
        "name": "李世民",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xB28A3DB1"],  # 1473
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "shouxing": {
        "name": "寿星",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xB4DA85C7"],
        "walk": ["shape.wdf", "0xBE41583A"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "daoshi": {
        "name": "道士",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xB7809CE0"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "xiaoshe": {
        "name": "小蛇",
        "run": ["shape.wdf", "0xD954D814"],
        "stand": ["shape.wdf", "0xB8217AF2"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "heshang": {
        "name": "和尚",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xE4926FC7"],
        "walk": ["shape.wdf", "0xBC6686FD"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "laohoujing": {
        "name": "老猴精",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xBDD0DC76"],
        "walk": ["shape.wdf", "0xC230BE81"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "nv_purple": {
        "name": "未知女",  # 梳头发
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xC82770E2"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "jiudianlaoban_2": {
        "name": "酒店老板",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xC888F0C3"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "yizhan": {
        "name": "驿站",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xD02A9BB5"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "lu": {
        "name": "鹿",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xEC3FC0DC"],
        "walk": ["shape.wdf", "0xD4D2D232"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "caifengdianlaoban": {
        "name": "裁缝店老板",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xD6C941FC"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "nongfu_hat": {
        "name": "农夫",  # 帽子
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xD7A74DE2"],
        "walk": ["shape.wdf", "0xF846C711"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "nv_blue_purple": {
        "name": "未知女",  # 女 蓝色上衣 紫色裙子
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xD97E30F0"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "qianzhuanglaoban_2": {
        "name": "钱庄老板",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xDA498AD2"],  # 1537
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "baise_bird": {
        "name": "白色小鸟",
        "stand": ["shape.wdf", "0xDE318B4E"],
        "fly": ["shape.wdf", "0xE6914BD4"]
    },
    "huichuntanglaoban": {
        "name": "回春堂老板",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xE0DC6D93"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "zhongkui": {
        "name": "钟馗",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xF1E86993"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "qingfengmingyue": {
        "name": "清风明月",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xF4848781"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "qianzhuanglaoban_3": {
        "name": "钱庄老板",
        "run": ["", "0x"],
        "stand": ["", "0x"],
        "walk": ["shape.wdf", "0xF637E75A"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "tangseng": {
        "name": "唐僧",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xF707EA37"],
        "walk": ["shape.wdf", "0xFF76393B"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "nv_green_purple": {
        "name": "未知女",
        "run": ["", "0x"],
        "stand": ["shape.wdf", "0xFF25D8BA"],
        "walk": ["", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "suanpan_man": {
        "name": "算盘男",
        "run": ["shape.wd1", "0x125EFE92"],
        "jag": ["shape.wd1", "0x47FE008A"],
        "stand1": ["shape.wd1", "0x083CE816"],
        "stand2": ["shape.wd1", "0x95EC9E1E"],
        "stand": ["shape.wd1", "0x5688BCEF"],
        "walk": ["shape.wd1", "0x2CD24689"],
        "hit": ["shape.wd1", "0x2425D416"],
        "beaten": ["shape.wd1", "0xD851D6E2"],
        "defence": ["shape.wd1", "0xF337B69C"],
        "magic": ["shape.wd1", "0x5CF5551D"],
        "static": ["", "0x"],
        "beaten_down": ["shape.wd1", "0xF11F5A3F"],
        "dead": ["", "0x"],
    },
    "blue_thin_man": {
        "name": "蓝色瘦商贾戴头巾",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0xEC0DF38A"],
        "walk": ["shape.wd1", "0x0CF18EFD"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "dachui_man": {
        "name": "大锤男",
        "run": ["shape.wd1", "0xE8C3530A"],
        "run_9": ["shape.wd1", "0xBEBC542D"],
        "stand_9": [["shape.wd1", "0x7C093B0D"], ["shape.wd1", "0xE1E7C0DB"]],  # 113
        "stand": ["shape.wd1", "0x88131C90"],
        "walk": ["shape.wd1", "0x"],
        "walk_9": ["shape.wd1", "0xF5E3731D"],
        "hit": ["shape.wd1", "0x5787BE65"],
        "beaten": ["shape.wd1", "0x7B7905BF"],
        "defence": ["shape.wd1", "0x97BBF022"],
        "magic": ["shape.wd1", "0x0EFDC0D1"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x11CCB1CD"],
    },
    "beikuang_man": {
        "name": "背筐男",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0x6341E0D6"],
        "walk": ["shape.wd1", "0x177CDA70"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "shipolan": {
        "name": "石破烂",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0x1D232BFA"],
        "walk": ["shape.wd1", "0x5DBA1EE4"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["", "0x"],
    },
    "shuangdao_woman": {
        "name": "双刀女",
        "run": ["shape.wd1", "0x5059E6D6"],
        "run_9": ["shape.wd1", "0xCC562036"],
        "stand": ["shape.wd1", "0x292FB2BF"],
        "stand_9": [["shape.wd1", "0xA7D2163C"], ["shape.wd1", "0xFB7F9483"]],
        "walk": ["shape.wd1", "0x91BE6BE7"],
        "hit": ["shape.wd1", "0xF1F826F4"],
        "beaten": ["shape.wd1", "0xAE989F8F"],
        "defence": ["shape.wd1", "0xF197C006"],
        "magic": ["shape.wd1", "0x252CBF89"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x22CA45C2"],
    },
    "xiaojuren": {
        "name": "萧举人",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0x39DA26FF"],
        "walk": ["shape.wd1", "0x290B7A68"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "shensuanzi": {
        "name": "神算子",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0xD5A91213"],
        "walk": ["shape.wd1", "0x2AF8E37F"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "licaijin": {
        "name": "李财进",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0x673FB7FB"],
        "walk": ["shape.wd1", "0x31D892E2"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "laotou_guaigun": {
        "name": "拐棍老头",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0x5E578EF1"],
        "walk": ["shape.wd1", "0x33727B1C"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "dingtianzhu": {
        "name": "顶天柱",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0x42E7C21B"],
        "walk": ["shape.wd1", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "yizhanlaoban": {
        "name": "驿站老板",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0x5D1C654C"],
        "walk": ["shape.wd1", "0x62F5CF03"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "shanghuizongguan": {
        "name": "商会总管",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0xDCD3450F"],
        "walk": ["shape.wd1", "0x61234CD5"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "huqiaoer": {
        "name": "胡巧儿",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0x636012E7"],
        "walk": ["shape.wd1", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "guanyuan": {  # 紫色，胖
        "name": "官员紫色胖",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0xA1EFE980"],
        "walk": ["shape.wd1", "0x67FFD6C6"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "hooker": {  #
        "name": "妓女",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0x76C9251E"],
        "walk": ["shape.wd1", "0xF1C6B3B3"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "toujin_man": {  # 绿裤子紫鞋
        "name": "头巾男",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0xC0C679A6"],
        "walk": ["shape.wd1", "0x80F80A68"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "datie_man": {  #
        "name": "打铁男",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0xA831A782"],
        "walk": ["shape.wd1", "0xA7362DEF"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "mantangchun": {  #
        "name": "满堂春",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0xD0A9859B"],
        "walk": ["shape.wd1", "0xC5E98CA8"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "huanghuoniu": {
        "name": "黄火牛",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0xD371D9CF"],
        "walk": ["shape.wd1", "0x"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
    "pipa_nv": {
        "name": "琵琶女",
        "run": ["shape.wd1", "0x"],
        "stand": ["shape.wd1", "0xE5218837"],
        "walk": ["shape.wd1", "0xFE3A270F"],
        "hit": ["", "0x"],
        "beaten": ["", "0x"],
        "defence": ["", "0x"],
        "magic": ["shape.wd1", "0x"],
        "static": ["", "0x"],
        "beaten_down": ["", "0x"],
        "dead": ["shape.wd1", "0x"],
    },
}


# "": {
#     "name": "",
#     "run": ["", "0x"],
#     "stand": ["", "0x"],
#     "walk": ["", "0x"],
#     "hit": ["", "0x"],
#     "beaten": ["", "0x"],
#     "defence": ["", "0x"],
#     "magic": ["", "0x"],
#     "static": ["", "0x"],
#     "beaten_down": ["", "0x"],
#     "dead": ["", "0x"],
# },